import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireOwnerRole } from "./auth-guards.server";

const id=z.string().uuid();
const rules=z.object({min_discount:z.number().finite().min(0).max(100),min_trend_velocity:z.number().finite().min(0),min_demand_score:z.number().finite().min(0),min_offer_score:z.number().finite().min(0),require_active_offer:z.boolean()});
async function client(){const {supabaseAdmin}=await import("@/integrations/supabase/client.server");return supabaseAdmin;}
export const listSmartCollections=createServerFn({method:"GET"}).middleware([requireOwnerRole]).handler(async()=>{const c=await client();const {data,error}=await c.from("curated_collections").select("id,slug,title,description,collection_type,candidate_rules,is_active,created_at,updated_at").order("created_at",{ascending:false});if(error)throw new Error(error.message);return data??[];});
export const saveSmartCollection=createServerFn({method:"POST"}).middleware([requireOwnerRole]).inputValidator((v)=>z.object({id:id.optional(),title:z.string().trim().min(1).max(200),slug:z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(200),description:z.string().trim().max(5000).nullable(),collection_type:z.enum(["achadinhos","trending","offers","category","seasonal","personalized","editorial"]),candidate_rules:rules,is_active:z.boolean()}).parse(v)).handler(async({data})=>{const c=await client();const {id:rowId,...payload}=data;const q=rowId?c.from("curated_collections").update(payload as any).eq("id",rowId):c.from("curated_collections").insert(payload as any);const {data:row,error}=await q.select().single();if(error)throw new Error(error.message);return row;});
export const generateSmartCandidates=createServerFn({method:"POST"}).middleware([requireOwnerRole]).inputValidator((v)=>id.parse(v)).handler(async({data})=>{const c=await client();const {data:result,error}=await c.rpc("generate_collection_candidates",{p_collection_id:data});if(error)throw new Error(error.message);return result;});
export const simulateSmartCandidates=createServerFn({method:"POST"}).middleware([requireOwnerRole]).inputValidator((v)=>z.object({collectionId:id,rules}).parse(v)).handler(async({data})=>{const c=await client();const {data:result,error}=await c.rpc("simulate_collection_candidates",{p_collection_id:data.collectionId,p_rules:data.rules});if(error)throw new Error(error.message);return result;});
export const reviewSmartCandidate=createServerFn({method:"POST"}).middleware([requireOwnerRole]).inputValidator((v)=>z.object({candidateId:id,action:z.enum(["approve","reject"])}).parse(v)).handler(async({data})=>{const c=await client();const fn=data.action==="approve"?"approve_collection_candidate":"reject_collection_candidate";const {data:result,error}=await c.rpc(fn,{p_candidate_id:data.candidateId});if(error)throw new Error(error.message);return result;});
export const prioritizeSmartCandidate=createServerFn({method:"POST"}).middleware([requireOwnerRole]).inputValidator((v)=>z.object({candidateId:id,priority:z.number().int().min(0)}).parse(v)).handler(async({data})=>{const c=await client();const {data:row,error}=await c.from("collection_candidates").update({priority:data.priority}).eq("id",data.candidateId).eq("status","pending").select().single();if(error)throw new Error(error.message);return row;});
export const listSmartCandidates=createServerFn({method:"GET"}).middleware([requireOwnerRole]).inputValidator((v)=>id.parse(v)).handler(async({data})=>{const c=await client();const {data:rows,error}=await c.from("collection_candidates").select("id,collection_id,product_id,matched_signal,status,priority,suggested_at,reviewed_at,products(title,current_price,discount,trend_velocity,demand_score,offer_score)").eq("collection_id",data).order("priority",{ascending:false}).order("suggested_at",{ascending:false});if(error)throw new Error(error.message);return (rows??[]).map((row:any)=>({...row,product:Array.isArray(row.products)?row.products[0]:row.products}));});