import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireOwnerRole } from '@/lib/auth-guards.server';
import { getIntegrationSecretServer } from '@/integrations/secrets.server';

const ConfigSchema = z.object({ channelId: z.string().trim().min(1).max(200), isActive: z.boolean(), botToken: z.string().trim().min(1).max(500).optional().nullable() });
const MessageSchema = z.object({ message: z.string().trim().min(1).max(4000).default('🧪 Mensagem de teste do Admin') });

async function getConfig(supabaseAdmin: any) { const { data, error } = await supabaseAdmin.from('telegram_config').select('id,channel_id,is_active,updated_at').maybeSingle(); if (error) throw error; return data as any; }
async function getTelegramCredentials() { const [token, channelId] = await Promise.all([getIntegrationSecretServer('telegram', 'bot_token'), getIntegrationSecretServer('telegram', 'channel_id')]); return { token: token?.trim() || null, channelId: channelId?.trim() || null }; }
async function callTelegram(token: string, method: string, body: Record<string, unknown>) { const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (!response.ok || !result?.ok) throw new Error(result?.description || `Telegram API HTTP ${response.status}`); return result; }

export const getTelegramConfig = createServerFn({ method: "GET" }).middleware([requireOwnerRole]).handler(async () => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const config = await getConfig(supabaseAdmin); const { token, channelId } = await getTelegramCredentials(); return config ? { id: config.id, channel_id: channelId || config.channel_id, is_active: config.is_active, hasToken: Boolean(token) } : { id: null, channel_id: channelId, is_active: false, hasToken: Boolean(token) }; });

export const saveTelegramConfig = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => ConfigSchema.parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const current = await getConfig(supabaseAdmin); const { error: configError } = current?.id ? await supabaseAdmin.from('telegram_config').update({ channel_id: data.channelId, is_active: data.isActive, bot_token_secret_ref: 'vault:telegram.bot_token', updated_at: new Date().toISOString() }).eq('id', current.id) : await supabaseAdmin.from('telegram_config').insert({ channel_id: data.channelId, is_active: data.isActive, bot_token_secret_ref: 'vault:telegram.bot_token' }); if (configError) throw configError; const { error: channelError } = await (supabaseAdmin as any).rpc('set_integration_secret', { p_platform_id: 'telegram', p_field_key: 'channel_id', p_value: data.channelId }); if (channelError) throw new Error(`Não foi possível salvar o Channel ID seguro: ${channelError.message}`); if (data.botToken) { const { error: tokenError } = await (supabaseAdmin as any).rpc('set_integration_secret', { p_platform_id: 'telegram', p_field_key: 'bot_token', p_value: data.botToken }); if (tokenError) throw new Error(`Não foi possível salvar o Bot Token seguro: ${tokenError.message}`); } return { success: true, hasToken: Boolean(data.botToken) || Boolean(await getIntegrationSecretServer('telegram', 'bot_token')) }; });

export const testTelegramConnection = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => MessageSchema.parse(data ?? {})).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const config = await getConfig(supabaseAdmin); if (!config?.is_active) return { success: false, error: 'Telegram integration is inactive.' }; const { token, channelId } = await getTelegramCredentials(); if (!token || !channelId) return { success: false, error: 'Telegram Bot Token ou Channel ID não está configurado no Secure Hub.' }; try { const result = await callTelegram(token, 'sendMessage', { chat_id: channelId, text: data.message }); return { success: true, telegram_message_id: result.result?.message_id ?? null }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : 'Telegram API request failed.' }; } });

export const composeTelegramMessage = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => z.object({ productId: z.string().uuid().optional(), offerGroupId: z.string().uuid().optional(), campaignId: z.string().uuid().optional() }).refine(v => Boolean(v.productId || v.offerGroupId)).parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); let q = supabaseAdmin.from('products').select('*, marketplaces(name)'); q = data.productId ? q.eq('id', data.productId) : q.eq('offer_group_id', data.offerGroupId!).eq('is_best_offer', true); const { data: product, error } = await q.maybeSingle(); if (error) throw error; if (!product) return { error: 'Product not found' }; const p = product as any; const url = String(p.affiliate_url || '').trim(); if (!url) return { error: 'Product has no affiliate URL.' }; return { message: [`🔥 <b>${escapeHtml(String(p.title))}</b>`, '', `💰 De: <s>R$ ${p.previous_price?.toLocaleString('pt-BR') || '---'}</s>`, `✅ <b>Por: R$ ${Number(p.current_price).toLocaleString('pt-BR')}</b>`, `📉 Desconto: ${p.discount ?? 0}% OFF`, '', `📍 Vendido por: ${escapeHtml(String(p.marketplaces?.name || 'Parceiro'))}`, '', `🔗 <a href="${escapeHtml(url)}">Compre aqui</a>`].join('\n') }; });
function escapeHtml(value: string) { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }

export const sendTelegramManual = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => z.object({ productId: z.string().uuid(), message: z.string().trim().min(1).max(4000) }).parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const config = await getConfig(supabaseAdmin); const { token, channelId } = await getTelegramCredentials(); if (!config?.is_active) return { success: false, error: 'Telegram integration not active' }; if (!token || !channelId) return { success: false, error: 'Telegram Bot Token ou Channel ID não está configurado no Secure Hub.' }; try { const result = await callTelegram(token, 'sendMessage', { chat_id: channelId, text: data.message, parse_mode: 'HTML' }); const { error } = await supabaseAdmin.from('telegram_messages').insert({ product_id: data.productId, message_text: data.message, status: 'sent', sent_at: new Date().toISOString() }); if (error) throw error; return { success: true, telegram_message_id: result.result?.message_id ?? null }; } catch (error) { await supabaseAdmin.from('telegram_messages').insert({ product_id: data.productId, message_text: data.message, status: 'failed', sent_at: null }); return { success: false, error: error instanceof Error ? error.message : 'Telegram API request failed.' }; } });