import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireOwnerRole } from '@/lib/auth-guards.server';

const ConfigSchema = z.object({ channelId: z.string().trim().min(1).max(200), isActive: z.boolean(), botToken: z.string().trim().min(10).max(300).optional().nullable() });
async function getConfig(supabaseAdmin: any) { const { data, error } = await supabaseAdmin.from('telegram_config' as any).select('*').maybeSingle(); if (error) throw error; return data as any; }

export const getTelegramConfig = createServerFn({ method: "GET" }).middleware([requireOwnerRole]).handler(async () => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const c = await getConfig(supabaseAdmin); return c ? { id: c.id, channel_id: c.channel_id, is_active: c.is_active, hasToken: Boolean(c.bot_token_secret_ref) } : null; });

export const saveTelegramConfig = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => ConfigSchema.parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const current = await getConfig(supabaseAdmin); const payload: Record<string, unknown> = { channel_id: data.channelId, is_active: data.isActive, updated_at: new Date().toISOString() }; if (data.botToken) payload.bot_token_secret_ref = `telegram:${crypto.randomUUID()}`; const { error } = current?.id ? await supabaseAdmin.from('telegram_config' as any).update(payload).eq('id', current.id) : await supabaseAdmin.from('telegram_config' as any).insert(payload); if (error) throw error; return { success: true }; });

export const testTelegramConnection = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => z.object({ message: z.string().trim().min(1).max(4000).default('🧪 Mensagem de teste do Admin') }).parse(data ?? {})).handler(async () => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const c = await getConfig(supabaseAdmin); if (!c?.is_active) return { success: false, error: 'Telegram integration is inactive.' }; return { success: false, error: 'Telegram token is referenced but no secure server-side secret provider is configured for this deployment.' }; });

export const composeTelegramMessage = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => z.object({ productId: z.string().uuid().optional(), offerGroupId: z.string().uuid().optional(), campaignId: z.string().uuid().optional() }).refine(v => Boolean(v.productId || v.offerGroupId)).parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); let q = supabaseAdmin.from('products').select('*, marketplaces(name)'); q = data.productId ? q.eq('id', data.productId) : q.eq('offer_group_id', data.offerGroupId!).eq('is_best_offer', true); const { data: product, error } = await q.maybeSingle(); if (error) throw error; if (!product) return { error: 'Product not found' }; const p = product as any; return { message: [`🔥 *${String(p.title).toUpperCase()}*`, '', `💰 De: ~R$ ${p.previous_price?.toLocaleString('pt-BR') || '---'}~`, `✅ *Por: R$ ${Number(p.current_price).toLocaleString('pt-BR')}*`, `📉 Desconto: ${p.discount ?? 0}% OFF`, '', `📍 Vendido por: ${p.marketplaces?.name || 'Parceiro'}`, '', `🔗 Compre aqui: ${p.affiliate_url}${p.affiliate_url?.includes('?') ? '&' : '?'}utm_source=telegram${data.campaignId ? `&campaign_id=${data.campaignId}` : ''}`].join('\n') }; });

export const sendTelegramManual = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => z.object({ productId: z.string().uuid(), message: z.string().trim().min(1).max(4000) }).parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const c = await getConfig(supabaseAdmin); if (!c?.is_active) return { success: false, error: 'Telegram integration not active' }; const { error } = await supabaseAdmin.from('telegram_messages' as any).insert({ product_id: data.productId, message_text: data.message, status: 'failed', sent_at: null }); if (error) throw error; return { success: false, error: 'Telegram token is not available through a configured secure server-side secret provider.' }; });
