import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireOwnerRole } from '@/lib/auth-guards.server';

const ConfigSchema = z.object({ channelId: z.string().trim().min(1).max(200), isActive: z.boolean() });
async function getConfig(supabaseAdmin: any) { const { data, error } = await supabaseAdmin.from('telegram_config' as any).select('*').maybeSingle(); if (error) throw error; return data as any; }
function getTelegramToken() { const token = process.env['TELEGRAM_BOT_TOKEN']?.trim(); return token || null; }
async function callTelegram(token: string, method: string, body: Record<string, unknown>) { const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (!response.ok || !result?.ok) throw new Error(result?.description || `Telegram API HTTP ${response.status}`); return result; }

export const getTelegramConfig = createServerFn({ method: "GET" }).middleware([requireOwnerRole]).handler(async () => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const c = await getConfig(supabaseAdmin); return c ? { id: c.id, channel_id: c.channel_id, is_active: c.is_active, hasToken: Boolean(getTelegramToken()) } : null; });

export const saveTelegramConfig = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => ConfigSchema.parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const current = await getConfig(supabaseAdmin); const payload = { channel_id: data.channelId, is_active: data.isActive, bot_token_secret_ref: 'env:TELEGRAM_BOT_TOKEN', updated_at: new Date().toISOString() }; const { error } = current?.id ? await supabaseAdmin.from('telegram_config' as any).update(payload).eq('id', current.id) : await supabaseAdmin.from('telegram_config' as any).insert(payload); if (error) throw error; return { success: true, hasToken: Boolean(getTelegramToken()) }; });

export const testTelegramConnection = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => z.object({ message: z.string().trim().min(1).max(4000).default('🧪 Mensagem de teste do Admin') }).parse(data ?? {})).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const c = await getConfig(supabaseAdmin); if (!c?.is_active) return { success: false, error: 'Telegram integration is inactive.' }; const token = getTelegramToken(); if (!token) return { success: false, error: 'TELEGRAM_BOT_TOKEN is not configured on the server.' }; try { const result = await callTelegram(token, 'sendMessage', { chat_id: c.channel_id, text: data.message }); return { success: true, telegram_message_id: result.result?.message_id ?? null }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : 'Telegram API request failed.' }; } });

export const composeTelegramMessage = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => z.object({ productId: z.string().uuid().optional(), offerGroupId: z.string().uuid().optional(), campaignId: z.string().uuid().optional() }).refine(v => Boolean(v.productId || v.offerGroupId)).parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); let q = supabaseAdmin.from('products').select('*, marketplaces(name)'); q = data.productId ? q.eq('id', data.productId) : q.eq('offer_group_id', data.offerGroupId!).eq('is_best_offer', true); const { data: product, error } = await q.maybeSingle(); if (error) throw error; if (!product) return { error: 'Product not found' }; const p = product as any; return { message: [`🔥 *${String(p.title).toUpperCase()}*`, '', `💰 De: ~R$ ${p.previous_price?.toLocaleString('pt-BR') || '---'}~`, `✅ *Por: R$ ${Number(p.current_price).toLocaleString('pt-BR')}*`, `📉 Desconto: ${p.discount ?? 0}% OFF`, '', `📍 Vendido por: ${p.marketplaces?.name || 'Parceiro'}`, '', `🔗 Compre aqui: ${p.affiliate_url}${p.affiliate_url?.includes('?') ? '&' : '?'}utm_source=telegram${data.campaignId ? `&campaign_id=${data.campaignId}` : ''}`].join('\n') }; });

export const sendTelegramManual = createServerFn({ method: "POST" }).middleware([requireOwnerRole]).validator((data: unknown) => z.object({ productId: z.string().uuid(), message: z.string().trim().min(1).max(4000) }).parse(data)).handler(async ({ data }) => { const { supabaseAdmin } = await import('@/integrations/supabase/client.server'); const c = await getConfig(supabaseAdmin); if (!c?.is_active) return { success: false, error: 'Telegram integration not active' }; const token = getTelegramToken(); if (!token) return { success: false, error: 'TELEGRAM_BOT_TOKEN is not configured on the server.' }; let result: any; try { result = await callTelegram(token, 'sendMessage', { chat_id: c.channel_id, text: data.message, parse_mode: 'Markdown' }); } catch (error) { await supabaseAdmin.from('telegram_messages' as any).insert({ product_id: data.productId, message_text: data.message, status: 'failed', sent_at: null }); return { success: false, error: error instanceof Error ? error.message : 'Telegram API request failed.' }; } const { error } = await supabaseAdmin.from('telegram_messages' as any).insert({ product_id: data.productId, message_text: data.message, status: 'sent', sent_at: new Date().toISOString() }); if (error) throw error; return { success: true, telegram_message_id: result.result?.message_id ?? null }; });
