import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Crown, Eye, EyeOff, Medal, RefreshCw, Trophy } from "lucide-react";
import { getLeaderboard, getUserReferralStats, updateLeaderboardVisibility } from "@/lib/supabase/tiers";

export function ReferralLeaderboard({ userId }: { userId?: string | null }) {
  const client = useQueryClient();
  const leaderboard = useQuery({ queryKey: ["referral-leaderboard"], queryFn: () => getLeaderboard(50), staleTime: 30_000 });
  const stats = useQuery({ queryKey: ["referral-stats", userId], queryFn: () => getUserReferralStats(userId!), enabled: !!userId, staleTime: 30_000 });
  const visibility = useMutation({ mutationFn: updateLeaderboardVisibility, onSuccess: () => { client.invalidateQueries({ queryKey: ["referral-stats", userId] }); client.invalidateQueries({ queryKey: ["referral-leaderboard"] }); } });
  return <section className="space-y-4 rounded-[2rem] border border-glass-border bg-glass p-5 sm:p-6 backdrop-blur-xl shadow-xl">
    <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Trophy className="h-5 w-5" /></div><div><h2 className="text-lg font-black uppercase italic">Ranking de indicadores</h2><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Somente usuários que escolheram aparecer</p></div></div><div className="flex gap-2">{userId && <button type="button" onClick={() => visibility.mutate(!stats.data?.showOnLeaderboard)} disabled={visibility.isPending} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-glass-border px-3 text-[9px] font-black uppercase tracking-widest hover:bg-primary/10">{stats.data?.showOnLeaderboard ? <><Eye className="h-4 w-4" /> Público</> : <><EyeOff className="h-4 w-4" /> Oculto</>}</button>}<button type="button" onClick={() => leaderboard.refetch()} className="grid h-10 w-10 place-items-center rounded-xl border border-glass-border" aria-label="Atualizar ranking"><RefreshCw className="h-4 w-4" /></button></div></header>
    {leaderboard.isLoading ? <div className="py-12 text-center text-sm font-bold text-muted-foreground">Carregando ranking...</div> : leaderboard.data?.length ? <div className="space-y-2">{leaderboard.data.map((item) => <div key={item.userId} className={`flex items-center gap-3 rounded-2xl border p-3 ${item.userId === userId ? "border-primary bg-primary/5" : "border-glass-border bg-white/[.02]"}`}><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-muted/40">{item.position === 1 ? <Crown className="h-4 w-4" /> : item.position <= 3 ? <Medal className="h-4 w-4" /> : <span className="text-xs font-black">{item.position}</span>}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-black uppercase">{item.name}{item.userId === userId ? " · você" : ""}</p><p className="text-[9px] font-black uppercase tracking-widest" style={{ color: item.tierColor }}>{item.tierIcon} {item.tierName}</p></div><div className="text-right"><p className="text-lg font-black tabular-nums">{item.totalReferrals}</p><p className="text-[8px] font-black uppercase tracking-widest text-muted-foreground">ativadas</p></div></div>)}</div> : <div className="rounded-2xl border border-dashed border-glass-border py-12 text-center"><Trophy className="mx-auto h-8 w-8 text-muted-foreground/30" /><p className="mt-3 text-xs font-black uppercase tracking-widest text-muted-foreground">Nenhum indicador público ainda</p></div>}
  </section>;
}
