import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useSuspenseQuery, useQuery } from "@tanstack/react-query";
import { getPersonalizedFeed } from "@/lib/personalization.functions";
import { getPublicHomeModules } from "@/lib/admin-modules.functions";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ProductCard } from "@/components/product/ProductCard";
import { TrendingUp, Zap, ArrowRight, ShieldCheck, Globe, Sparkles } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { CategoryStrip } from "@/components/product/CategoryStrip";
import { BannerCarousel } from "@/components/product/BannerCarousel";
import { FlashDeals } from "@/components/product/FlashDeals";
import { CategoryHighlightsSection } from "@/components/product/CategoryHighlightsSection";
import { ContinueBrowsing } from "@/components/product/ContinueBrowsing";

export const Route = createFileRoute("/")({
  loader: async ({ context }: { context: any }) => { try { await context.queryClient.ensureQueryData({ queryKey: ["personalizedFeed", null, 4], queryFn: () => getPersonalizedFeed({ data: { userId: null, limit: 4 } }) }); } catch (e) { console.error("Loader feed error:", e); } },
  component: Index,
  head: () => ({ title: "AFFILIATEPRO | Discovery & Video Commerce", meta: [{ name: "description", content: "A próxima geração do comércio liderado por descoberta. Compras em vídeo imersivas e ofertas inteligentes." }, { property: "og:title", content: "AFFILIATEPRO — Plataforma de Afiliados Moderna" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
});

function Index() {
  const navigate = useNavigate();
  const { data: products } = useSuspenseQuery({ queryKey: ["personalizedFeed", null, 4], queryFn: () => getPersonalizedFeed({ data: { userId: null, limit: 4 } }) });
  const { data: modules = [] } = useQuery({ queryKey: ["public-home-modules"], queryFn: () => getPublicHomeModules(), staleTime: 30_000 });
  const enabled = new Set(modules.map((m) => m.module_key));
  const show = (key: string) => enabled.size === 0 || enabled.has(key);

  return <div className="flex min-h-screen w-full flex-col gap-0">
    {show("hero") && <section className="relative flex min-h-[95vh] items-center justify-center overflow-hidden bg-background pt-20"><div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute left-[-10%] top-[-10%] aspect-square w-[60%] rounded-full bg-primary/10 blur-[150px] animate-pulse" /><div className="absolute bottom-[-10%] right-[-10%] aspect-square w-[50%] rounded-full bg-blue-600/10 blur-[130px]" /></div><div className="z-10 mx-auto max-w-7xl space-y-10 px-4 text-center"><Badge variant="outline" className="glass-surface rounded-full border-primary/30 bg-primary/5 px-5 py-2 text-primary"><Sparkles className="mr-2 h-3.5 w-3.5" />PROTOCOLO DE INTELIGÊNCIA ATIVO</Badge><h1 className="text-6xl font-black uppercase italic leading-[0.85] tracking-[-0.06em] md:text-[8rem]">O FUTURO <br />DAS <span className="text-primary mix-blend-plus-lighter">OFERTAS</span> <br />HOJE.</h1><p className="mx-auto max-w-2xl text-xl font-medium leading-relaxed tracking-tight text-muted-foreground md:text-2xl">Comércio de próxima geração impulsionado por algoritmos de descoberta ponderada. Rastreamento em tempo real. Inteligência máxima.</p><div className="flex flex-wrap justify-center gap-6 pt-6"><Button size="lg" className="group h-16 rounded-2xl px-10 text-xl font-black shadow-2xl shadow-primary/30 transition-all hover:scale-105" asChild><Link to="/feed">ENTRAR NO SISTEMA<ArrowRight className="ml-3 h-6 w-6 transition-transform group-hover:translate-x-1" /></Link></Button><Button size="lg" variant="outline" className="glass-surface h-16 rounded-2xl px-10 text-xl font-bold transition-all hover:bg-primary/5" onClick={async () => { const { data: { user } } = await supabase.auth.getUser(); if (user) navigate({ to: "/profile" }); else navigate({ to: "/auth" }); }}>SINCRONIZAR PERFIL</Button></div></div></section>}
    {show("continue_browsing") && <ContinueBrowsing />}
    {show("categories") && <CategoryStrip />}
    {show("banners") && <BannerCarousel />}
    {show("featured_video") && <section className="mx-auto w-full max-w-7xl px-4 py-12"><div className="relative flex min-h-[400px] flex-col overflow-hidden rounded-[2.5rem] border border-glass-border bg-glass-fallback shadow-2xl md:flex-row"><div className="relative aspect-video w-full bg-black md:aspect-auto md:w-1/2"><div className="absolute inset-0 flex items-center justify-center"><div className="space-y-4 text-center"><Badge className="bg-primary/20 font-black uppercase tracking-widest text-primary">Lançamento Ativo</Badge><h3 className="text-3xl font-black uppercase italic tracking-tighter text-white">Revelação Coleção de Verão</h3><Button className="gap-2 rounded-xl font-black uppercase italic shadow-2xl shadow-primary/20"><Link to="/videos">Assistir Estreia</Link></Button></div></div></div><div className="flex w-full flex-col justify-center space-y-6 p-12 md:w-1/2"><Badge variant="outline" className="w-fit border-primary/20 text-[10px] font-black uppercase tracking-widest text-primary">Acesso Exclusivo</Badge><h2 className="text-4xl font-black uppercase italic leading-none tracking-tighter md:text-5xl">O Futuro da <br/><span className="text-primary">Moda Tech</span></h2><p className="text-lg font-medium text-muted-foreground">Experimente a próxima geração de wearables em comércio de vídeo de alta definição. Compre diretamente do frame.</p><div className="flex gap-4"><div className="flex flex-col"><span className="text-2xl font-black italic">42.5K</span><span className="text-[9px] font-black uppercase tracking-widest opacity-40">Visualizações</span></div><div className="h-10 w-px bg-glass-border" /><div className="flex flex-col"><span className="text-2xl font-black italic">120+</span><span className="text-[9px] font-black uppercase tracking-widest opacity-40">Produtos</span></div></div></div></div></section>}
    {show("flash_deals") && <FlashDeals />}
    {show("category_highlights") && <CategoryHighlightsSection limit={4} />}
    {show("trust_bar") && <section className="border-y bg-muted/20 py-12"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-8 px-4 opacity-60 md:justify-between"><Link to="/videos" className="group flex cursor-pointer items-center gap-2 text-lg font-bold transition-colors hover:text-primary"><Zap className="h-5 w-5 group-hover:animate-pulse" />COMÉRCIO EM VÍDEO</Link><div className="flex items-center gap-2 text-lg font-bold"><Globe className="h-5 w-5" />BUSCA GLOBAL</div><div className="flex items-center gap-2 text-lg font-bold"><ShieldCheck className="h-5 w-5 text-emerald-500" />CENTRO DE CONFORMIDADE</div><div className="flex items-center gap-2 text-lg font-bold"><TrendingUp className="h-5 w-5" />PREÇO EM TEMPO REAL</div></div></section>}
    {show("personalized_feed") && products && products.length > 0 && <section className="mx-auto w-full max-w-7xl px-4 py-24"><div className="mb-12 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="space-y-2"><Badge variant="secondary" className="rounded-full border border-white/5 bg-white/5 px-4 text-[10px] font-black uppercase tracking-widest">Tendências Agora</Badge><h2 className="text-4xl font-black uppercase italic tracking-tighter md:text-6xl">Descoberta Personalizada</h2></div><Button variant="ghost" className="group text-xs font-bold uppercase tracking-widest" asChild><Link to="/feed">Ver Tudo<ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></Button></div><div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map((product: any) => <div key={product.id} className="group/card relative">{product.feedContext && <div className="absolute -top-3 left-4 z-20 rounded-full border border-white/5 bg-background/80 px-3 py-1 shadow-xl backdrop-blur-md"><span className="text-[9px] font-black uppercase tracking-[0.15em] text-primary/70">{product.feedContext}</span></div>}<ProductCard id={product.id} slug={product.slug} categoryId={product.categoryId} title={product.title} price={product.price} previousPrice={product.previousPrice} discount={product.discount} image={product.image} marketplace={product.marketplace} rating={product.rating} reviewCount={product.reviewCount} affiliateUrl={product.affiliateUrl ?? null} hasVideo={product.hasVideo} isBestOffer={product.isBestOffer} offerScore={product.offerScore} /></div>)}</div></section>}
    {show("cta") && <section className="relative overflow-hidden bg-primary px-4 py-32 pb-[140px] text-primary-foreground selection:bg-white/20 selection:text-white md:pb-32"><div className="relative z-10 mx-auto max-w-4xl space-y-8 text-center"><h2 className="text-4xl font-black uppercase italic leading-none tracking-[-0.06em] md:text-8xl">PRONTO PARA DAR UM UPGRADE NAS SUAS COMPRAS?</h2><p className="text-xl font-medium leading-relaxed tracking-tight text-primary-foreground/70 md:text-2xl">Junte-se a milhares de usuários que encontram os melhores preços na Amazon, Mercado Livre e muito mais usando nosso motor de descoberta orientado por IA.</p><div className="flex justify-center gap-4 pt-6"><Button size="lg" variant="secondary" className="h-16 rounded-2xl px-12 text-xl font-black uppercase tracking-tight shadow-2xl transition-all hover:scale-105" asChild><Link to="/register">Criar Conta Gratuita</Link></Button></div></div></section>}
  </div>;
}
