import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { getAdminMarketingAnalytics } from "@/lib/admin-analytics.functions";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Activity, Zap, TrendingUp, BarChart3, MousePointerClick, Eye, Clock3 } from "lucide-react";

export const Route = createFileRoute("/admin/analytics")({ component: AdminAnalyticsPage });

function AdminAnalyticsPage() {
  const getAnalytics = useServerFn(getAdminMarketingAnalytics);
  const { data, isLoading, isError } = useQuery({ queryKey: ["admin-marketing-analytics", 30], queryFn: () => getAnalytics({ data: { days: 30 } }), staleTime: 60_000 });
  const totalEvents = data?.events.length ?? 0;
  const popupViews = data?.views ?? 0;
  const popupClicks = data?.clicks ?? 0;
  const popupCtr = popupViews ? popupClicks / popupViews * 100 : 0;
  const generalCtr = (data?.generalViews ?? 0) ? (data?.generalClicks ?? 0) / (data?.generalViews ?? 1) * 100 : 0;
  const cards = [["Eventos", totalEvents, Activity], ["Exibições", popupViews, Eye], ["Cliques", popupClicks, MousePointerClick], ["CTR pop-ups", `${popupCtr.toFixed(2)}%`, TrendingUp], ["CTR geral", `${generalCtr.toFixed(2)}%`, Zap]] as const;
  return <div className="container mx-auto max-w-7xl space-y-8 px-4 py-8 pb-safe sm:px-6 lg:px-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><Badge variant="outline">Marketing Intelligence · 30 dias</Badge><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-5xl">Analytics</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Métricas reais do comportamento registrado no sistema.</p></div><Badge variant="outline">{isLoading ? "Sincronizando…" : isError ? "Erro" : "LIVE DATA"}</Badge></header>
    {isError && <Card><CardContent className="py-12 text-center text-destructive">Não foi possível carregar as métricas. Atualize a página e tente novamente.</CardContent></Card>}
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-5">{cards.map(([label,value,Icon])=><Card key={label} className="rounded-3xl"><CardContent className="p-5"><Icon className="mb-3 h-4 w-4 text-primary"/><p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black sm:text-3xl">{typeof value === "number" ? value.toLocaleString("pt-BR") : value}</p></CardContent></Card>)}</div>
    <div className="grid gap-6 lg:grid-cols-2"><Card className="rounded-[2rem]"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest">CTR por estratégia</CardTitle></CardHeader><CardContent className="space-y-3">{data?.byStrategy.map((r:any)=><div key={r.strategy} className="flex items-center justify-between rounded-2xl border p-4"><div><p className="text-xs font-black uppercase">{r.strategy}</p><p className="text-xs text-muted-foreground">{r.views} visualizações · {r.clicks} cliques</p></div><Badge variant="outline">{r.ctr.toFixed(2)}%</Badge></div>)}</CardContent></Card><Card className="rounded-[2rem]"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest">CTR por gatilho</CardTitle></CardHeader><CardContent className="space-y-3">{data?.timing.length ? data.timing.map((r:any)=><div key={r.trigger} className="flex items-center justify-between rounded-2xl border p-4"><div><p className="text-xs font-black uppercase">{r.trigger}</p><p className="text-xs text-muted-foreground">{r.views} views · {r.clicks} clicks</p></div><Badge variant="outline">{r.ctr.toFixed(2)}%</Badge></div>) : <p className="py-8 text-center text-sm text-muted-foreground">Sem eventos de pop-up no período.</p>}</CardContent></Card></div>
    <Card className="overflow-hidden rounded-[2rem]"><CardHeader><CardTitle className="flex items-center gap-2 text-sm font-black uppercase tracking-widest"><Clock3 className="h-4 w-4 text-primary"/>Performance por horário</CardTitle></CardHeader><CardContent><div className="grid grid-cols-4 gap-2 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-12">{data?.hour.map((h:any)=><div key={h.hour} className="rounded-xl border p-2 text-center"><p className="text-[9px] font-black">{String(h.hour).padStart(2,"0")}h</p><p className="mt-1 text-xs font-bold">{h.views}</p><p className="text-[8px] text-muted-foreground">views</p></div>)}</div></CardContent></Card>
    <Card className="rounded-3xl"><CardContent className="p-6"><div className="flex items-start gap-3"><BarChart3 className="mt-0.5 h-5 w-5 text-primary"/><div><p className="text-xs font-black uppercase tracking-widest">ROI</p><p className="mt-1 text-sm font-bold">{data?.roiAvailable ? "Há dados de comissão real disponíveis." : "Pendente — nenhuma comissão real disponível. Nenhum ROI foi inventado."}</p></div></div></CardContent></Card>
    <Card className="overflow-hidden rounded-[2rem]"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest">Eventos recentes</CardTitle></CardHeader><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Evento</TableHead><TableHead>Origem</TableHead><TableHead>Usuário</TableHead><TableHead className="text-right">Horário</TableHead></TableRow></TableHeader><TableBody>{data?.events.slice(0,20).map((e:any)=><TableRow key={e.id}><TableCell><Badge variant="outline">{e.event_type}</Badge></TableCell><TableCell className="text-xs">{e.source ?? "—"}</TableCell><TableCell className="font-mono text-xs">{e.user_id ? `${e.user_id.slice(0,8)}…` : "anonymous"}</TableCell><TableCell className="whitespace-nowrap text-right text-xs">{new Date(e.created_at).toLocaleString("pt-BR")}</TableCell></TableRow>)}</TableBody></Table></div></Card>
    <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">A/B: {data?.experiments.filter((e:any)=>e.is_active).length ?? 0} experimento(s) ativo(s) · {data?.assignments.length ?? 0} atribuições nos últimos 30 dias</p>
  </div>;
}
