import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { Check, RefreshCw, Sparkles, X, Zap } from "lucide-react";

export const Route = createFileRoute("/admin/collections")({ ssr: false, component: AdminCollectionsPage });
const db = supabase as any;
type Collection = { id:string; slug:string; title:string; description:string|null; collection_type:string; candidate_rules:Record<string,unknown>; is_active:boolean };
type Candidate = { id:string; matched_signal:Record<string,unknown>; status:string; priority:number; product?: {title:string; discount:number|null; trend_velocity:number; demand_score:number; offer_score:number|null}|null };
const TYPES=["achadinhos","trending","offers","category","seasonal","personalized","editorial"];
const fresh=()=>({title:"",slug:"",description:"",collection_type:"achadinhos",is_active:false,min_discount:"20",min_trend_velocity:"0",min_demand_score:"0",min_offer_score:"0",require_active_offer:false});

function AdminCollectionsPage(){
 const [collections,setCollections]=useState<Collection[]>([]); const [selectedId,setSelectedId]=useState(""); const [candidates,setCandidates]=useState<Candidate[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [simulation,setSimulation]=useState<{count:number;samples:{title:string}[]}|null>(null); const [form,setForm]=useState(fresh());
 const selected=collections.find(c=>c.id===selectedId)??null;
 const rules=()=>({min_discount:Number(form.min_discount)||0,min_trend_velocity:Number(form.min_trend_velocity)||0,min_demand_score:Number(form.min_demand_score)||0,min_offer_score:Number(form.min_offer_score)||0,require_active_offer:form.require_active_offer});
 async function loadCandidates(id:string){const {data,error}=await db.from("collection_candidates").select("id,matched_signal,status,priority,products(title,discount,trend_velocity,demand_score,offer_score)").eq("collection_id",id).eq("status","pending").order("priority",{ascending:false}).order("suggested_at",{ascending:false});if(error){toast.error(error.message);return}setCandidates((data??[]).map((x:any)=>({...x,product:Array.isArray(x.products)?x.products[0]:x.products})));}
 async function load(){setLoading(true);try{const {data,error}=await db.from("curated_collections").select("id,slug,title,description,collection_type,candidate_rules,is_active").order("created_at",{ascending:false});if(error)throw error;setCollections(data??[]);if(selectedId)await loadCandidates(selectedId);}catch(e){toast.error(e instanceof Error?e.message:"Erro ao carregar coleções.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]); useEffect(()=>{if(selectedId)void loadCandidates(selectedId)},[selectedId]);
 function choose(c:Collection){setSelectedId(c.id);const r=c.candidate_rules??{};setForm({title:c.title,slug:c.slug,description:c.description??"",collection_type:c.collection_type,is_active:c.is_active,min_discount:String(r.min_discount??20),min_trend_velocity:String(r.min_trend_velocity??0),min_demand_score:String(r.min_demand_score??0),min_offer_score:String(r.min_offer_score??0),require_active_offer:Boolean(r.require_active_offer)});setSimulation(null)}
 function newCollection(){setSelectedId("");setForm(fresh());setSimulation(null)}
 async function save(){if(!form.title.trim()||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(form.slug.trim())){toast.error("Informe título e slug válido.");return}setBusy(true);try{const payload={title:form.title.trim(),slug:form.slug.trim(),description:form.description.trim()||null,collection_type:form.collection_type,candidate_rules:rules(),is_active:form.is_active};const q=selected?db.from("curated_collections").update(payload).eq("id",selected.id):db.from("curated_collections").insert(payload);const {data,error}=await q.select("*").single();if(error)throw error;setSelectedId(data.id);toast.success("Coleção salva.");await load();choose(data as Collection)}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setBusy(false)}}
 async function simulate(){if(!selectedId){toast.error("Salve a coleção antes de simular.");return}setBusy(true);try{const {data,error}=await db.rpc("simulate_collection_candidates",{p_collection_id:selectedId,p_rules:rules()});if(error)throw error;setSimulation(data)}catch(e){toast.error(e instanceof Error?e.message:"Falha na simulação.")}finally{setBusy(false)}}
 async function generate(){if(!selectedId)return;setBusy(true);try{const {data,error}=await db.rpc("generate_collection_candidates",{p_collection_id:selectedId});if(error)throw error;toast.success(`${Number(data?.generated??0)} candidato(s) processado(s).`);await loadCandidates(selectedId)}catch(e){toast.error(e instanceof Error?e.message:"Falha ao gerar candidatos.")}finally{setBusy(false)}}
 async function review(id:string,action:"approve"|"reject"){setBusy(true);try{const fn=action==="approve"?"approve_collection_candidate":"reject_collection_candidate";const {error}=await db.rpc(fn,{p_candidate_id:id});if(error)throw error;toast.success(action==="approve"?"Aprovado e publicado na coleção interna.":"Candidato rejeitado.");await loadCandidates(selectedId)}catch(e){toast.error(e instanceof Error?e.message:"Falha na revisão.")}finally{setBusy(false)}}
 async function prioritize(id:string,p:number){const {error}=await db.from("collection_candidates").update({priority:p+1}).eq("id",id).eq("status","pending");if(error)toast.error(error.message);else await loadCandidates(selectedId)}
 if(loading)return <div className="p-8">Carregando Smart Collection Engine...</div>;
 return <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:justify-between sm:items-end"><div><Badge variant="outline">SPRINT 28 • HUMAN APPROVAL</Badge><h1 className="text-3xl sm:text-4xl font-black uppercase italic tracking-tight mt-2">Smart Collections</h1><p className="text-muted-foreground">Motor de sugestões com aprovação humana obrigatória.</p></div><Button variant="outline" onClick={()=>void load()}><RefreshCw className="w-4 h-4 mr-2"/>Atualizar</Button></header>
 <Tabs defaultValue="engine"><TabsList><TabsTrigger value="engine">Motor & Regras</TabsTrigger><TabsTrigger value="queue">Candidatos <Badge className="ml-2">{candidates.length}</Badge></TabsTrigger></TabsList>
 <TabsContent value="engine" className="mt-5"><div className="grid lg:grid-cols-[280px_1fr] gap-5"><aside className="rounded-2xl border p-4 space-y-2"><div className="flex justify-between items-center mb-3"><h2 className="font-black uppercase text-sm">Coleções</h2><Button size="sm" onClick={newCollection}>+</Button></div>{collections.map(c=><button key={c.id} onClick={()=>choose(c)} className={`w-full text-left rounded-xl border p-3 ${selectedId===c.id?"border-primary bg-primary/10":"hover:bg-muted"}`}><b className="block truncate">{c.title}</b><span className="text-xs text-muted-foreground">{c.collection_type} • {c.is_active?"Ativa":"Rascunho"}</span></button>)}{!collections.length&&<p className="text-sm text-muted-foreground">Crie a primeira coleção.</p>}</aside>
 <section className="rounded-2xl border p-5 space-y-5"><div className="grid md:grid-cols-2 gap-4"><div><Label>Nome</Label><Input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></div><div><Label>Slug</Label><Input value={form.slug} onChange={e=>setForm(f=>({...f,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")}))}/></div></div><div><Label>Tipo</Label><Select value={form.collection_type} onValueChange={v=>setForm(f=>({...f,collection_type:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{TYPES.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></div><div><Label>Descrição</Label><Textarea value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></div><div className="rounded-xl border p-4"><h3 className="font-black uppercase text-sm mb-4 flex gap-2"><Sparkles className="w-4 h-4"/>Regras AND</h3><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{([["min_discount","Desconto mínimo %"],["min_trend_velocity","Trend velocity ≥"],["min_demand_score","Demand score ≥"],["min_offer_score","Offer score ≥"]] as const).map(([k,l])=><div key={k}><Label>{l}</Label><Input type="number" step="0.1" value={form[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></div>)}</div><label className="flex gap-2 mt-4 text-sm"><input type="checkbox" checked={form.require_active_offer} onChange={e=>setForm(f=>({...f,require_active_offer:e.target.checked}))}/> Exigir melhor oferta ativa</label></div><div className="flex flex-wrap gap-2"><Button onClick={()=>void save()} disabled={busy}>{busy?"Processando...":"Salvar coleção"}</Button><Button variant="secondary" onClick={()=>void simulate()} disabled={busy}>Simular regra</Button>{selected&&<Button variant="outline" onClick={()=>void generate()} disabled={busy}><Zap className="w-4 h-4 mr-2"/>Gerar candidatos</Button>}</div>{simulation&&<div className="rounded-xl border border-primary/30 bg-primary/5 p-4"><b>Simulação: {simulation.count} produto(s)</b><p className="text-xs text-muted-foreground mt-1">Não grava nem publica nada.</p>{simulation.samples?.slice(0,5).map((s,i)=><div key={i} className="text-sm mt-1">• {s.title}</div>)}</div>}<label className="flex gap-3 border rounded-xl p-4"><input type="checkbox" checked={form.is_active} onChange={e=>setForm(f=>({...f,is_active:e.target.checked}))}/><span><b>Disponível publicamente</b><small className="block text-muted-foreground">Somente itens aprovados aparecem.</small></span></label></section></div></TabsContent>
 <TabsContent value="queue" className="mt-5 space-y-4"><div className="flex justify-between items-center"><div><h2 className="text-xl font-black uppercase italic">Fila de aprovação</h2><p className="text-sm text-muted-foreground">Nada desta fila entra em collection_items sem aprovação.</p></div>{selected&&<Button onClick={()=>void generate()} disabled={busy}><Zap className="w-4 h-4 mr-2"/>Gerar</Button>}</div>{!selected?<div className="border border-dashed rounded-xl p-10 text-center">Selecione uma coleção.</div>:!candidates.length?<div className="border border-dashed rounded-xl p-10 text-center text-muted-foreground"><Sparkles className="mx-auto mb-2"/>Nenhum candidato pendente.</div>:candidates.map(c=><div key={c.id} className="border rounded-2xl p-4 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="flex gap-2"><Badge variant="outline">Prioridade {c.priority}</Badge><Badge>Pendente</Badge></div><b className="block mt-2">{c.product?.title??"Produto"}</b><div className="text-sm text-muted-foreground mt-1">Desconto {Number(c.product?.discount??c.matched_signal.discount??0)}% • Trend {Number(c.product?.trend_velocity??c.matched_signal.trend_velocity??0)} • Demand {Number(c.product?.demand_score??c.matched_signal.demand_score??0)} • Offer {Number(c.product?.offer_score??c.matched_signal.offer_score??0)}</div></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>void prioritize(c.id,c.priority)} disabled={busy}>Priorizar</Button><Button size="sm" variant="destructive" onClick={()=>void review(c.id,"reject")} disabled={busy}><X className="w-4 h-4 mr-1"/>Rejeitar</Button><Button size="sm" onClick={()=>void review(c.id,"approve")} disabled={busy}><Check className="w-4 h-4 mr-1"/>Aprovar</Button></div></div>)}</TabsContent></Tabs></div>;
}