import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Database, Link2, ExternalLink, RefreshCw, AlertCircle, CheckCircle2, Clock, Edit3, Save, Globe, Plus } from "lucide-react";
import { toast } from "sonner";
import { useState } from "react";

export const Route = createFileRoute("/admin/marketplaces")({ component: AdminMarketplacesPage });

function AdminMarketplacesPage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [editingMarketplace, setEditingMarketplace] = useState<any>(null);
  const [linkStructure, setLinkStructure] = useState("");
  const { data: marketplaces, isLoading } = useQuery({ queryKey: ["admin-marketplaces"], queryFn: async () => { const { data, error } = await supabase.from("marketplaces").select("id, name, slug, status, api_status, created_at, affiliate_link_structure").order("name", { ascending: true }); if (error) throw error; return data; } });
  const updateStatusMutation = useMutation({ mutationFn: async ({ id, status }: { id: string; status: string }) => { const { error } = await supabase.from("marketplaces").update({ status }).eq("id", id); if (error) throw error; }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["admin-marketplaces"] }); toast.success("Marketplace status updated"); }, onError: (error) => toast.error(`Failed: ${error.message}`) });
  const updateStructureMutation = useMutation({ mutationFn: async ({ id, structure }: { id: string; structure: string }) => { const { error } = await supabase.from("marketplaces").update({ affiliate_link_structure: structure } as any).eq("id", id); if (error) throw error; }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["admin-marketplaces"] }); toast.success("Affiliate structure updated"); setEditingMarketplace(null); }, onError: (error) => toast.error(`Failed: ${error.message}`) });
  const getStatusIcon = (status: string) => status === "connected" ? <CheckCircle2 className="w-4 h-4 text-green-500" /> : status === "pending" ? <Clock className="w-4 h-4 text-yellow-500" /> : status === "error" ? <AlertCircle className="w-4 h-4 text-red-500" /> : <Link2 className="w-4 h-4 text-muted-foreground" />;
  const getStatusBadge = (status: string) => { const variants: Record<string, string> = { connected: "bg-green-500/10 text-green-500 border-green-500/20", pending: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20", error: "bg-red-500/10 text-red-500 border-red-500/20", disabled: "bg-muted/50 text-muted-foreground border-glass-border" }; return <Badge className={`rounded-full px-3 py-0.5 text-[10px] font-black uppercase ${variants[status] || variants.disabled}`}>{status}</Badge>; };
  return <div className="container mx-auto py-12 px-4 max-w-7xl space-y-8">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-6"><div className="space-y-2"><Badge className="bg-primary/10 text-primary border-primary/20 font-bold px-3">Connectors</Badge><h1 className="text-4xl md:text-5xl font-black tracking-tighter uppercase italic">MARKETPLACES</h1></div><div className="flex gap-3"><Button onClick={() => navigate({ to: "/admin/marketplaces/new" })} className="h-11 px-6 font-black gap-2 rounded-xl"><Plus className="w-4 h-4" />Add Marketplace</Button><Button variant="outline" className="h-11 px-6 font-bold gap-2 rounded-xl bg-background/50 border-glass-border"><RefreshCw className="w-4 h-4" />Re-sync All</Button></div></div>
    <div className="bg-glass-fallback border border-glass-border rounded-3xl overflow-hidden shadow-2xl"><Table><TableHeader className="bg-muted/30"><TableRow><TableHead className="font-black py-6 pl-8">Marketplace</TableHead><TableHead>Slug</TableHead><TableHead>Status</TableHead><TableHead>API</TableHead><TableHead>Link Logic</TableHead><TableHead className="text-right pr-8">Control</TableHead></TableRow></TableHeader><TableBody>{isLoading ? [...Array(3)].map((_, i) => <TableRow key={i}><TableCell className="pl-8 py-6"><div className="h-4 w-32 bg-muted animate-pulse rounded" /></TableCell><TableCell /><TableCell /><TableCell /><TableCell /><TableCell /></TableRow>) : marketplaces?.map((m) => <TableRow key={m.id} className="hover:bg-white/5"><TableCell className="font-bold py-6 pl-8"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary"><Database className="w-4 h-4" /></div>{m.name}</div></TableCell><TableCell className="font-mono text-xs text-muted-foreground">{m.slug}</TableCell><TableCell><div className="flex items-center gap-2">{getStatusIcon(m.status ?? "")}{getStatusBadge(m.status ?? "")}</div></TableCell><TableCell className="text-xs">{m.api_status || "Pending Verification"}</TableCell><TableCell className="font-mono text-[9px] text-muted-foreground max-w-[150px] truncate">{(m as any).affiliate_link_structure || "Standard"}</TableCell><TableCell className="text-right pr-8"><div className="flex justify-end gap-2"><Button variant="ghost" size="sm" onClick={() => updateStatusMutation.mutate({ id: m.id, status: m.status === "disabled" ? "pending" : "disabled" })}>{m.status === "disabled" ? "ENABLE" : "DISABLE"}</Button><Dialog open={editingMarketplace?.id === m.id} onOpenChange={(open) => { if (!open) setEditingMarketplace(null); else { setEditingMarketplace(m); setLinkStructure((m as any).affiliate_link_structure || ""); } }}><DialogTrigger asChild><Button variant="ghost" size="icon"><Edit3 className="w-3.5 h-3.5" /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Link Logic: {m.name}</DialogTitle></DialogHeader><div className="space-y-5 py-4"><Label>Affiliate Link Structure</Label><Input value={linkStructure} onChange={e => setLinkStructure(e.target.value)} placeholder="https://.../{id}?tag=..." /><Button className="w-full" onClick={() => updateStructureMutation.mutate({ id: m.id, structure: linkStructure })} disabled={updateStructureMutation.isPending}><Save className="w-4 h-4 mr-2" />{updateStructureMutation.isPending ? "Saving..." : "Save Structure"}</Button></div></DialogContent></Dialog><Button variant="ghost" size="icon" asChild><a href={`/admin/marketplaces/${m.id}`} aria-label={`Abrir ${m.name}`}><ExternalLink className="w-3.5 h-3.5" /></a></Button></div></TableCell></TableRow>)}</TableBody></Table></div>
  </div>;
}
