import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Plus, Pencil, Trash2, Layers, RefreshCw, Search, Star, ExternalLink } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { getOfferGroups, getOfferGroupDetails, saveOfferGroup, deleteOfferGroup } from "@/lib/admin_intel.functions";
import { OfferFeaturedControl } from "@/components/admin/offers/OfferFeaturedControl";
import { CouponAdmin } from "@/components/admin/coupons/CouponAdmin";

export const Route = createFileRoute("/admin/offers")({ component: AdminOffersPage });
function AdminOffersPage() {
  const navigate = useNavigate(); const qc = useQueryClient(); const getGroups = useServerFn(getOfferGroups); const getDetails = useServerFn(getOfferGroupDetails); const saveGroup = useServerFn(saveOfferGroup); const removeGroup = useServerFn(deleteOfferGroup);
  const [editing,setEditing]=useState<{id:string;canonical_title:string}|null>(null); const [saving,setSaving]=useState(false); const [query,setQuery]=useState("");
  const {data:groups,isLoading,isError,error,refetch}=useQuery({queryKey:["admin-offer-groups"],queryFn:()=>getGroups({data:{} as never})});
  const visibleGroups=useMemo(()=> (groups??[]).filter((g:any)=>String(g.canonical_title??"").toLowerCase().includes(query.toLowerCase())),[groups,query]); const featuredCount=(groups??[]).filter((g:any)=>g.is_featured_on_hub).length;
  const edit=async(id:string)=>{try{const result=await getDetails({data:{id}});setEditing({id,canonical_title:(result.group as any).canonical_title});}catch(e:any){toast.error(e?.message||"Não foi possível carregar a oferta.")}};
  const save=async()=>{if(!editing?.canonical_title.trim()){toast.error("Informe o nome da oferta.");return}setSaving(true);try{await saveGroup({data:{id:editing.id,canonical_title:editing.canonical_title.trim()}});toast.success("Oferta atualizada.");setEditing(null);await qc.invalidateQueries({queryKey:["admin-offer-groups"]})}catch(e:any){toast.error(e?.message||"Não foi possível atualizar a oferta.")}finally{setSaving(false)}};
  const remove=async(id:string)=>{if(!window.confirm("Excluir esta oferta? Produtos vinculados precisam ser desvinculados antes."))return;try{await removeGroup({data:{id}});toast.success("Oferta excluída.");await qc.invalidateQueries({queryKey:["admin-offer-groups"]})}catch(e:any){toast.error(e?.message||"Não foi possível excluir a oferta.")}};
  return <div className="relative min-h-[80vh] overflow-hidden"><div className="pointer-events-none absolute inset-x-0 top-0 h-96 bg-gradient-to-b from-primary/[0.08] via-primary/[0.025] to-transparent"/><div className="relative container mx-auto max-w-7xl space-y-8 px-4 py-10">
    <header className="overflow-hidden rounded-[2rem] border border-border/60 bg-card/70 p-6 shadow-elevation-1 backdrop-blur-xl sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.22em] text-primary"><Layers className="h-3.5 w-3.5"/>Offer Intelligence</div><div className="flex flex-wrap items-center gap-3"><h1 className="text-4xl font-black tracking-[-0.04em] sm:text-5xl">Ofertas</h1><Badge variant="outline" className="gap-1 rounded-full border-primary/20 bg-primary/5 text-primary"><Star className="h-3 w-3"/>{featuredCount} em destaque</Badge></div><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Organize grupos, controle destaques e mantenha a vitrine pública alinhada ao catálogo real.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="h-11 rounded-xl" onClick={()=>refetch()} disabled={isLoading}><RefreshCw className={isLoading?"animate-spin":""}/>Atualizar</Button><Button variant="outline" className="h-11 rounded-xl" onClick={()=>navigate({to:"/offers"})}><ExternalLink/>Ver loja</Button><Button onClick={()=>navigate({to:"/admin/offers/new"})} className="h-11 rounded-xl px-5 font-black"><Plus/>Nova oferta</Button></div></div></header>
    <div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar grupos de ofertas..." className="h-12 rounded-2xl border-border/60 bg-card/70 pl-11 shadow-sm backdrop-blur-xl"/></div>
    <OfferFeaturedControl/><CouponAdmin/>
    {isError&&<Card className="border-destructive/30"><CardContent className="flex flex-col items-start justify-between gap-4 p-6 sm:flex-row sm:items-center"><p className="text-sm font-medium text-destructive">{(error as any)?.message||"Erro ao carregar ofertas."}</p><Button variant="outline" onClick={()=>refetch()}>Tentar novamente</Button></CardContent></Card>}
    {!isError&&isLoading&&<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-44 animate-pulse rounded-[2rem] border border-border/60 bg-muted/40"/>)}</div>}
    {!isLoading&&!isError&&visibleGroups.length===0&&<Card className="rounded-[2rem] border-dashed border-border/70 bg-card/50"><CardContent className="p-12 text-center"><Layers className="mx-auto mb-4 h-10 w-10 text-muted-foreground"/><p className="font-bold">{query?"Nenhuma oferta encontrada.":"Nenhuma oferta cadastrada."}</p><p className="mt-1 text-sm text-muted-foreground">{query?"Tente outro termo de busca.":"Crie a primeira oferta para começar a organizar o catálogo."}</p></CardContent></Card>}
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visibleGroups.map((group:any)=><Card key={group.id} className="group overflow-hidden rounded-[2rem] border-border/60 bg-card/70 shadow-sm backdrop-blur-xl transition-all hover:-translate-y-0.5 hover:shadow-elevation-1"><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-lg font-black tracking-tight">{group.canonical_title}</CardTitle><p className="mt-1 text-xs text-muted-foreground">ID {group.id.slice(0,8)}</p></div><Badge variant={group.is_featured_on_hub?"default":"outline"}>{group.is_featured_on_hub?"Destaque":"Normal"}</Badge></div></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl border border-border/60 bg-background/40 p-3"><span className="text-muted-foreground">Prioridade</span><strong className="mt-1 block text-sm">{group.featured_priority??0}</strong></div><div className="rounded-xl border border-border/60 bg-background/40 p-3"><span className="text-muted-foreground">Atualização</span><strong className="mt-1 block text-sm">{new Date(group.updated_at||group.created_at).toLocaleDateString("pt-BR")}</strong></div></div><div className="flex gap-2"><Button variant="outline" className="flex-1 rounded-xl" onClick={()=>edit(group.id)}><Pencil/>Editar</Button><Button variant="destructive" size="icon" className="rounded-xl" onClick={()=>remove(group.id)} title="Excluir oferta"><Trash2/></Button></div></CardContent></Card>)}</div>
    {editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4 backdrop-blur-md"><Card className="w-full max-w-lg rounded-[2rem] border-border/60 bg-card shadow-2xl"><CardHeader><Badge variant="outline" className="mb-2 w-fit rounded-full">Edição</Badge><CardTitle className="text-2xl font-black tracking-tight">Editar oferta</CardTitle></CardHeader><CardContent className="space-y-5"><div className="space-y-2"><label htmlFor="offer-edit-name" className="text-sm font-bold">Nome da oferta</label><Input id="offer-edit-name" value={editing.canonical_title} onChange={e=>setEditing({...editing,canonical_title:e.target.value})} disabled={saving} autoFocus className="h-12 rounded-xl"/><p className="text-xs text-muted-foreground">A alteração é salva no grupo real de ofertas.</p></div><div className="flex justify-end gap-2"><Button variant="outline" className="rounded-xl" onClick={()=>setEditing(null)} disabled={saving}>Cancelar</Button><Button className="rounded-xl font-bold" onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar alterações"}</Button></div></CardContent></Card></div>}
  </div></div>;
}
