import { createFileRoute } from '@tanstack/react-router';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { getSocialProofConfig, updateSocialProofConfig } from '@/lib/social-proof.functions';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { Save, ShieldCheck } from 'lucide-react';
import { useState, useEffect } from 'react';

export const Route = createFileRoute('/admin/social-proof')({ component: SocialProofAdmin });

function SocialProofAdmin() {
  const queryClient = useQueryClient();
  const { data: config, isLoading } = useQuery({ queryKey: ['socialProofConfig'], queryFn: () => getSocialProofConfig() });
  const [formData, setFormData] = useState<any>(null);
  useEffect(() => { if (config) setFormData({ is_enabled: (config as any).is_enabled, allowed_event_types: (config as any).allowed_event_types || [], min_interval_seconds: (config as any).min_interval_seconds || 30, recency_window_minutes: (config as any).recency_window_minutes || 120, show_aggregated_counters: (config as any).show_aggregated_counters ?? true, min_events_for_counter: (config as any).min_events_for_counter || 5, counter_window_hours: (config as any).counter_window_hours || 24 }); }, [config]);
  const updateMutation = useMutation({ mutationFn: (data: any) => updateSocialProofConfig({ data }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['socialProofConfig'] }); toast.success('Configurações salvas com sucesso'); }, onError: (error) => { toast.error('Erro ao salvar configurações'); console.error(error); } });
  if (isLoading || !formData) return <div className="p-8">Carregando...</div>;
  const eventTypes = [
    { id: 'ADD_FAVORITE', label: 'Favoritados' }, { id: 'OUTBOUND_CLICK', label: 'Cliques em ofertas' }, { id: 'VIDEO_COMPLETE', label: 'Vídeo assistido até o fim' }, { id: 'BADGE_UNLOCKED', label: 'Badge desbloqueado' }, { id: 'REFERRAL_ACTIVATED', label: 'Indicação ativada' }
  ];
  return <div className="p-8 max-w-4xl mx-auto space-y-8">
    <div className="flex justify-between items-center"><div><h1 className="text-3xl font-black italic uppercase tracking-tighter">Social Proof Core</h1><p className="text-muted-foreground">Prova social baseada exclusivamente em eventos reais.</p></div><Button onClick={() => updateMutation.mutate(formData)} className="gap-2 font-black uppercase italic" disabled={updateMutation.isPending}><Save size={18}/>Salvar Alterações</Button></div>
    <Card className="glass-surface border-glass-border"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest">Status global</CardTitle><CardDescription>Somente eventos reais podem alimentar os pop-ups públicos.</CardDescription></CardHeader><CardContent className="flex items-center justify-between"><div><Label>Habilitar pop-ups</Label><p className="text-xs text-muted-foreground">Exibe eventos reais recentes quando houver elegibilidade.</p></div><Switch checked={formData.is_enabled} onCheckedChange={(v)=>setFormData({...formData,is_enabled:v})}/></CardContent></Card>
    <Card className="glass-surface border-glass-border"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest flex items-center gap-2"><ShieldCheck size={16}/>Protocolo de veracidade</CardTitle><CardDescription>Simulação, volume boost e dados fictícios não são configuráveis em produção.</CardDescription></CardHeader><CardContent><p className="text-xs text-muted-foreground">Eventos de compra, clique, favorito, vídeo, badge, indicação e contadores agregados usam somente registros reais.</p></CardContent></Card>
    <Card className="glass-surface border-glass-border"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest">Eventos elegíveis</CardTitle><CardDescription>Escolha quais ações reais podem alimentar a prova social.</CardDescription></CardHeader><CardContent className="grid grid-cols-1 sm:grid-cols-2 gap-4">{eventTypes.map(type=><div key={type.id} className="flex items-center space-x-2 p-3 rounded-xl bg-white/5 border border-white/5"><Checkbox id={type.id} checked={formData.allowed_event_types.includes(type.id)} onCheckedChange={(checked)=>setFormData({...formData,allowed_event_types:checked?[...formData.allowed_event_types,type.id]:formData.allowed_event_types.filter((t:string)=>t!==type.id)})}/><Label htmlFor={type.id} className="font-bold">{type.label}</Label></div>)}</CardContent></Card>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6"><Card className="glass-surface border-glass-border"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest">Recência</CardTitle></CardHeader><CardContent className="flex items-center gap-4"><Input type="number" value={formData.recency_window_minutes} onChange={e=>setFormData({...formData,recency_window_minutes:Math.max(1,parseInt(e.target.value)||1)})} className="w-24 text-center font-bold"/><span className="text-sm">minutos</span></CardContent></Card><Card className="glass-surface border-glass-border"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest">Intervalo</CardTitle></CardHeader><CardContent className="flex items-center gap-4"><Input type="number" value={formData.min_interval_seconds} onChange={e=>setFormData({...formData,min_interval_seconds:Math.max(1,parseInt(e.target.value)||1)})} className="w-24 text-center font-bold"/><span className="text-sm">segundos</span></CardContent></Card></div>
    <Card className="glass-surface border-glass-border"><CardHeader><CardTitle className="text-sm font-black uppercase tracking-widest">Contadores agregados reais</CardTitle><CardDescription>Nenhum contador é criado artificialmente.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex items-center justify-between"><div><Label>Habilitar contadores</Label><p className="text-xs text-muted-foreground">Somente volume real acima do mínimo.</p></div><Switch checked={formData.show_aggregated_counters} onCheckedChange={v=>setFormData({...formData,show_aggregated_counters:v})}/></div><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div><Label className="text-xs font-black uppercase tracking-widest opacity-60">Mínimo de eventos</Label><Input type="number" value={formData.min_events_for_counter} onChange={e=>setFormData({...formData,min_events_for_counter:Math.max(1,parseInt(e.target.value)||1)})} className="mt-2 w-24 text-center font-bold"/></div><div><Label className="text-xs font-black uppercase tracking-widest opacity-60">Janela (horas)</Label><Input type="number" value={formData.counter_window_hours} onChange={e=>setFormData({...formData,counter_window_hours:Math.max(1,parseInt(e.target.value)||1)})} className="mt-2 w-24 text-center font-bold"/></div></div></CardContent></Card>
  </div>;
}
