import * as React from "react";
import { Link } from "@tanstack/react-router";
import { Search, ShoppingBag, Menu, User, Bell, Heart, Heart as FavoritesIcon, Play, Grid3X3, Tag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { supabase } from "@/integrations/supabase/client";
import { getNotifications, getFavorites } from "@/lib/engagement.functions";
import { useServerFn } from "@tanstack/react-start";

export function Navbar() {
  const [isScrolled, setIsScrolled] = React.useState(false); const [isMenuOpen, setIsMenuOpen] = React.useState(false); const [userId, setUserId] = React.useState<string | null>(null); const [isOwner, setIsOwner] = React.useState(false); const getNotifsFn = useServerFn(getNotifications); const getFavsFn = useServerFn(getFavorites); const [notifications, setNotifications] = React.useState<any[]>([]); const [favorites, setFavorites] = React.useState<any[]>([]);
  React.useEffect(() => { const handleScroll = () => setIsScrolled(window.scrollY > 10); window.addEventListener("scroll", handleScroll); supabase.auth.getUser().then(async ({ data: { user } }) => { if (!user) return; setUserId(user.id); const { data: hasRole } = await supabase.rpc("has_role", { _user_id: user.id, _role: "owner" }); setIsOwner(!!hasRole); }); return () => window.removeEventListener("scroll", handleScroll); }, []);
  React.useEffect(() => { if (!userId) return; getNotifsFn().then(setNotifications); getFavsFn({ data: {} }).then(setFavorites); const interval = setInterval(() => getNotifsFn().then(setNotifications), 30000); return () => clearInterval(interval); }, [userId, getNotifsFn, getFavsFn]);
  const unreadCount = notifications.filter((n) => !n.read).length; const favoritesCount = favorites.length;
  const navigation = [
    { to: "/feed", label: "Feed de Descoberta", icon: ShoppingBag }, { to: "/products", label: "Produtos", icon: ShoppingBag }, { to: "/categories", label: "Categorias", icon: Grid3X3 }, { to: "/deals", label: "Ofertas", icon: ShoppingBag }, { to: "/trending", label: "Em Alta", icon: ShoppingBag }, { to: "/videos", label: "Video Commerce", icon: Play }, { to: "/alerts", label: `Alertas${unreadCount > 0 ? ` (${unreadCount})` : ""}`, icon: Bell }, { to: "/favorites", label: `Favoritos${favoritesCount > 0 ? ` (${favoritesCount})` : ""}`, icon: FavoritesIcon }, { to: "/my-coupons", label: "Meus Cupons", icon: Tag }, { to: "/profile", label: "Perfil Neural", icon: User },
  ];
  const closeMenu = () => setIsMenuOpen(false); const signOut = async () => { closeMenu(); await supabase.auth.signOut(); window.location.href = "/auth"; };
  return <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-500 px-4 py-4 pt-safe safe-top ${isScrolled ? "glass-surface shadow-2xl" : "bg-transparent"}`}><div className="max-w-7xl mx-auto flex items-center justify-between gap-4"><Link to="/" className="flex items-center gap-3 group shrink-0"><div className="w-12 h-12 rounded-2xl bg-primary flex items-center justify-center text-primary-foreground shadow-2xl shadow-primary/30 group-hover:rotate-[10deg] transition-all duration-500"><ShoppingBag size={26} className="group-hover:scale-110 transition-transform" /></div><span className="text-2xl font-black tracking-[-0.07em] italic uppercase hidden sm:block leading-none">AFFILIATE<span className="text-primary">PRO</span></span></Link><div className="hidden lg:flex items-center gap-2 flex-1 max-w-2xl mx-6"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" /><Input placeholder="Buscar produtos..." className="pl-10 h-11 rounded-xl bg-glass border-glass-border" /></div></div><div className="flex items-center gap-2"><Button asChild variant="ghost" size="icon" className="hidden sm:flex"><Link to="/my-coupons" aria-label="Meus cupons"><Tag className="h-5 w-5" /></Link></Button><Button asChild variant="ghost" size="icon" className="hidden sm:flex"><Link to="/favorites" aria-label="Favoritos"><Heart className="h-5 w-5" /></Link></Button><Sheet open={isMenuOpen} onOpenChange={setIsMenuOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" aria-label="Abrir menu"><Menu /></Button></SheetTrigger><SheetContent side="right" className="bg-background/95 backdrop-blur-xl"><SheetHeader><SheetTitle>Navegação</SheetTitle></SheetHeader><div className="mt-6 flex flex-col gap-1">{navigation.map((item) => <Link key={item.to} to={item.to as any} onClick={closeMenu} className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold hover:bg-primary/10 hover:text-primary"><item.icon className="h-4 w-4" />{item.label}</Link>)}{userId && <><DropdownMenuSeparator /><button onClick={signOut} className="rounded-xl px-4 py-3 text-left text-sm font-bold text-destructive hover:bg-destructive/10">Sair</button></>}</div></SheetContent></Sheet></div></div></nav>;
}
