import { useEffect, useRef, useState } from 'react';
import { Maximize, Pause, Play, Volume2, VolumeX } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';

interface ProductVideoProps { videoUrl: string; title?: string | null; subtitle?: string | null; thumbnail?: string | null; initialTime?: number; onStart?: () => void; onComplete?: () => void; onProgress?: (seconds: number, duration: number) => void; }

export function ProductVideo({ videoUrl, title, subtitle, thumbnail, initialTime = 0, onStart, onComplete, onProgress }: ProductVideoProps) {
  const videoRef = useRef<HTMLVideoElement>(null); const lastProgressRef = useRef(0);
  const [playing, setPlaying] = useState(false); const [muted, setMuted] = useState(true); const [progress, setProgress] = useState(0); const [started, setStarted] = useState(false); const [completed, setCompleted] = useState(false);
  useEffect(() => { setPlaying(false); setProgress(0); setStarted(false); setCompleted(false); lastProgressRef.current = 0; }, [videoUrl]);
  useEffect(() => { const video = videoRef.current; if (!video || !Number.isFinite(initialTime) || initialTime <= 0) return; const seek = () => { if (Number.isFinite(video.duration) && video.duration > 0) video.currentTime = Math.min(initialTime, Math.max(0, video.duration - 0.5)); }; if (video.readyState >= 1) seek(); else video.addEventListener('loadedmetadata', seek, { once: true }); return () => video.removeEventListener('loadedmetadata', seek); }, [initialTime, videoUrl]);
  if (!videoUrl) return null;
  const togglePlay = async () => { const video = videoRef.current; if (!video) return; if (video.paused) { try { await video.play(); } catch { return; } setPlaying(true); } else { video.pause(); setPlaying(false); } };
  const toggleMute = () => { const video = videoRef.current; if (!video) return; video.muted = !video.muted; setMuted(video.muted); };
  const seek = (value: number[]) => { const video = videoRef.current; if (!video || !Number.isFinite(video.duration) || video.duration <= 0) return; video.currentTime = ((value[0] ?? 0) / 100) * video.duration; };
  const fullscreen = async () => { const video = videoRef.current; if (!video) return; if (document.fullscreenElement) await document.exitFullscreen(); else await video.requestFullscreen?.(); };
  return <div className="overflow-hidden rounded-[2rem] border border-glass-border bg-black shadow-2xl"><div className="relative aspect-square sm:aspect-video"><video ref={videoRef} src={videoUrl} poster={thumbnail || undefined} className="h-full w-full object-contain" playsInline muted={muted} preload="metadata" onPlay={() => { setPlaying(true); if (!started) { setStarted(true); onStart?.(); } }} onPause={() => setPlaying(false)} onTimeUpdate={() => { const video = videoRef.current; if (!video || !Number.isFinite(video.duration) || video.duration <= 0) return; const ratio = video.currentTime / video.duration; setProgress(ratio * 100); if (onProgress && video.currentTime - lastProgressRef.current >= 5) { lastProgressRef.current = video.currentTime; onProgress(video.currentTime, video.duration); } if (!completed && ratio >= 0.9) { setCompleted(true); onComplete?.(); } }} onEnded={() => { setPlaying(false); if (onProgress && videoRef.current) onProgress(videoRef.current.currentTime, videoRef.current.duration); }} onClick={togglePlay} />{!playing && <button type="button" onClick={togglePlay} aria-label="Reproduzir vídeo" className="absolute inset-0 m-auto h-16 w-16 rounded-full bg-primary/90 text-primary-foreground shadow-xl backdrop-blur-md transition-transform hover:scale-105"><Play className="mx-auto h-8 w-8 fill-current" /></button>}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-4 pt-10"><Slider value={[progress]} max={100} step={0.1} onValueChange={seek} aria-label="Progresso do vídeo" /><div className="mt-3 flex items-center justify-between"><div className="flex gap-2"><Button type="button" variant="ghost" size="icon" onClick={togglePlay} className="text-white hover:bg-white/15">{playing ? <Pause /> : <Play />}</Button><Button type="button" variant="ghost" size="icon" onClick={toggleMute} className="text-white hover:bg-white/15">{muted ? <VolumeX /> : <Volume2 />}</Button></div><Button type="button" variant="ghost" size="icon" onClick={fullscreen} className="text-white hover:bg-white/15" aria-label="Tela cheia"><Maximize /></Button></div></div></div>{(title || subtitle) && <div className="border-t border-white/10 bg-background/60 p-4">{title && <h3 className="text-sm font-black uppercase tracking-tight">{title}</h3>}{subtitle && <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{subtitle}</p>}</div>}</div>;
}
