import { useQuery, useQueryClient, useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Calendar, Clock, Send, Plus, X, Loader2, RefreshCw, Ban, CheckCircle2, AlertCircle, RotateCcw } from "lucide-react";
import { useState } from "react";
import { createScheduledPost, cancelScheduledPost, getScheduledPosts, processScheduledPosts, retryScheduledPost } from "@/lib/admin-publishing.functions";

type FormState = { content_type: string; content_id: string; channels: string[]; scheduled_for: string; message_template: string };
const initialForm: FormState = { content_type: "offer", content_id: "", channels: ["telegram"], scheduled_for: "", message_template: "" };

export function PublishingScheduler() {
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState<FormState>(initialForm);
  const getPosts = useServerFn(getScheduledPosts);
  const createPost = useServerFn(createScheduledPost);
  const cancelPost = useServerFn(cancelScheduledPost);
  const processPosts = useServerFn(processScheduledPosts);
  const retryPost = useServerFn(retryScheduledPost);
  const postsQuery = useQuery({ queryKey: ["admin", "scheduled-posts"], queryFn: () => getPosts() });

  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["admin", "scheduled-posts"] });
  const createMutation = useMutation({ mutationFn: () => createPost({ data: { ...form, content_type: form.content_type as "offer" | "video" | "bundle", channels: ["telegram"], scheduled_for: new Date(form.scheduled_for).toISOString(), message_template: form.message_template.trim() } }), onSuccess: () => { invalidate(); setForm(initialForm); setShowForm(false); } });
  const cancelMutation = useMutation({ mutationFn: (id: string) => cancelPost({ data: { id } }), onSuccess: invalidate });
  const processMutation = useMutation({ mutationFn: () => processPosts({ data: { limit: 10 } }), onSuccess: invalidate });
  const retryMutation = useMutation({ mutationFn: (id: string) => retryPost({ data: { id } }), onSuccess: invalidate });

  const submit = () => {
    if (!form.content_id || !form.scheduled_for || !form.message_template.trim()) return;
    if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(form.content_id)) return;
    if (new Date(form.scheduled_for).getTime() <= Date.now()) return;
    createMutation.mutate();
  };

  if (postsQuery.isLoading) return <div className="mx-auto max-w-6xl p-6 text-sm text-muted-foreground">Carregando publicações...</div>;
  if (postsQuery.isError) return <div className="mx-auto max-w-6xl p-6"><div className="rounded-xl border border-destructive/30 bg-destructive/5 p-5 text-sm text-destructive">{postsQuery.error instanceof Error ? postsQuery.error.message : "Erro ao carregar publicações."}<button className="ml-3 underline" onClick={() => postsQuery.refetch()}>Tentar novamente</button></div></div>;

  const posts = postsQuery.data ?? [];
  return <div className="mx-auto max-w-6xl space-y-6 p-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-semibold tracking-tight">Agendador de Publicações</h1><p className="mt-1 text-sm text-muted-foreground">Programe conteúdo e acompanhe o disparo automático.</p></div><div className="flex gap-2"><button className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm" onClick={() => postsQuery.refetch()}><RefreshCw size={15}/> Atualizar</button><button className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground" onClick={() => setShowForm(true)}><Plus size={15}/> Nova publicação</button></div></div>
    {showForm && <div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="font-semibold">Nova publicação</h2><button onClick={() => setShowForm(false)}><X size={18}/></button></div><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2 text-sm"><span>Tipo</span><select className="w-full rounded-lg border bg-background px-3 py-2" value={form.content_type} onChange={e => setForm({...form, content_type:e.target.value})}><option value="offer">Oferta</option><option value="video">Vídeo</option><option value="bundle">Produto/Combo</option></select></label><label className="space-y-2 text-sm"><span>ID do conteúdo (UUID)</span><input className="w-full rounded-lg border bg-background px-3 py-2" value={form.content_id} onChange={e => setForm({...form, content_id:e.target.value})} placeholder="Cole o UUID do conteúdo"/></label><label className="space-y-2 text-sm"><span>Data e hora</span><input type="datetime-local" className="w-full rounded-lg border bg-background px-3 py-2" value={form.scheduled_for} onChange={e => setForm({...form, scheduled_for:e.target.value})}/></label><div className="space-y-2 text-sm"><span>Canal</span><label className="flex items-center gap-2 rounded-lg border p-2"><input type="checkbox" checked readOnly/> Telegram</label><div className="rounded-lg border border-dashed p-2 text-xs text-muted-foreground">Outros canais permanecem bloqueados até existir conector real de publicação.</div></div><label className="space-y-2 text-sm md:col-span-2"><span>Mensagem</span><textarea className="min-h-28 w-full rounded-lg border bg-background px-3 py-2" value={form.message_template} onChange={e => setForm({...form, message_template:e.target.value})} placeholder="Confira nossa oferta exclusiva!"/></label></div>{createMutation.isError && <p className="mt-3 text-sm text-destructive">{createMutation.error instanceof Error ? createMutation.error.message : "Erro ao agendar."}</p>}<div className="mt-5 flex justify-end gap-2"><button className="rounded-lg border px-4 py-2 text-sm" onClick={() => setShowForm(false)}>Cancelar</button><button disabled={createMutation.isPending} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50" onClick={submit}>{createMutation.isPending ? <Loader2 className="animate-spin" size={15}/> : <Send size={15}/>} Agendar</button></div></div>}
    <div className="rounded-2xl border bg-card shadow-sm"><div className="border-b p-4"><h2 className="font-semibold">Fila de publicação</h2><p className="text-xs text-muted-foreground">{posts.length} registro(s)</p></div>{posts.length === 0 ? <div className="p-12 text-center text-muted-foreground"><Calendar className="mx-auto mb-3" size={40}/><p>Nenhuma publicação agendada.</p></div> : <div className="divide-y">{posts.map(post => <div key={post.id} className="flex flex-col gap-4 p-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border px-2 py-0.5 text-xs">{post.content_type}</span><span className="font-mono text-xs text-muted-foreground">{post.content_id.slice(0,8)}…</span></div><div className="mt-2 flex items-center gap-2 text-sm"><Clock size={14}/>{new Date(post.scheduled_for).toLocaleString()}</div><div className="mt-1 text-xs text-muted-foreground">{post.channels.join(", ")}</div>{post.error_message && <p className="mt-1 text-xs text-destructive">{post.error_message}</p>}</div><div className="flex items-center gap-3">{post.status === "published" ? <span className="inline-flex items-center gap-1 text-sm text-emerald-600"><CheckCircle2 size={15}/> Publicado</span> : post.status === "failed" ? <><span className="inline-flex items-center gap-1 text-sm text-destructive"><AlertCircle size={15}/> Falhou</span><button className="inline-flex items-center gap-1 rounded-lg border px-2 py-1 text-xs" disabled={retryMutation.isPending} onClick={() => retryMutation.mutate(post.id)}><RotateCcw size={13}/> Reprocessar</button></> : post.status === "processing" ? <span className="inline-flex items-center gap-1 text-sm"><Loader2 className="animate-spin" size={15}/> Processando</span> : <><span className="text-sm text-muted-foreground">Agendado</span><button className="inline-flex items-center gap-1 rounded-lg border px-2 py-1 text-xs" disabled={cancelMutation.isPending} onClick={() => cancelMutation.mutate(post.id)}><Ban size={13}/> Cancelar</button></>}</div></div>)}</div>}</div>
    <div className="flex justify-end"><button className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm" disabled={processMutation.isPending} onClick={() => processMutation.mutate()}>{processMutation.isPending ? <Loader2 className="animate-spin" size={15}/> : <Send size={15}/>} Processar agora</button></div>
    {processMutation.isSuccess && <p className="text-right text-xs text-muted-foreground">Processamento executado: {processMutation.data.processed} item(ns).</p>}{processMutation.isError && <p className="text-right text-sm text-destructive">{processMutation.error instanceof Error ? processMutation.error.message : "Erro ao processar fila."}</p>}
  </div>;
}
