import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowRight, Sparkles } from "lucide-react";

export const Route=createFileRoute("/collections/$slug")({component:SmartCollectionPage});
function SmartCollectionPage(){
 const {slug}=Route.useParams();
 const query=useQuery({queryKey:["smart-collection",slug],queryFn:async()=>{const {data,error}=await supabase.from("curated_collections").select("id,title,description,collection_type").eq("slug",slug).eq("is_active",true).maybeSingle();if(error)throw error;if(!data)return null;const items=await supabase.from("collection_items").select("position,products(id,slug,title,current_price,previous_price,discount,images,affiliate_url)").eq("collection_id",data.id).order("position",{ascending:true});if(items.error)throw items.error;return {...data,items:(items.data??[]).map((x:any)=>Array.isArray(x.products)?x.products[0]:x.products).filter(Boolean)};}});
 if(query.isLoading)return <main className="min-h-screen p-8"><div className="max-w-6xl mx-auto animate-pulse">Carregando coleção...</div></main>;
 if(query.isError)return <main className="min-h-screen p-8"><div className="max-w-3xl mx-auto rounded-2xl border p-10 text-center">Não foi possível carregar esta coleção.</div></main>;
 const collection=query.data;if(!collection)return <main className="min-h-screen p-8"><div className="max-w-3xl mx-auto rounded-2xl border p-10 text-center"><h1 className="text-2xl font-black">Coleção não encontrada</h1><Link to="/" className="inline-block mt-4"><Button>Voltar</Button></Link></div></main>;
 return <main className="min-h-screen p-4 sm:p-8"><div className="max-w-6xl mx-auto space-y-8"><header className="rounded-3xl border p-6 sm:p-10"><Badge variant="outline" className="mb-3"><Sparkles className="w-3 h-3 mr-1"/>{collection.collection_type}</Badge><h1 className="text-4xl sm:text-6xl font-black uppercase italic tracking-tight">{collection.title}</h1>{collection.description&&<p className="mt-3 text-muted-foreground max-w-2xl">{collection.description}</p>}<p className="mt-4 text-sm font-bold text-muted-foreground">{collection.items.length} produto(s) selecionado(s)</p></header>{collection.items.length===0?<div className="rounded-2xl border border-dashed p-12 text-center text-muted-foreground">Esta coleção ainda não possui produtos aprovados.</div>:<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">{collection.items.map((p:any)=><article key={p.id} className="rounded-2xl border bg-card overflow-hidden flex flex-col"><div className="aspect-square bg-muted overflow-hidden">{p.images?.[0]?<img src={p.images[0]} alt={p.title} loading="lazy" className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-muted-foreground">Sem imagem</div>}</div><div className="p-4 flex flex-col gap-2 flex-1"><h2 className="font-bold line-clamp-2">{p.title}</h2>{p.discount!=null&&Number(p.discount)>0&&<Badge className="w-fit">-{Number(p.discount)}%</Badge>}<div className="mt-auto pt-2"><div className="text-xl font-black">{p.current_price!=null?`R$ ${Number(p.current_price).toFixed(2)}`:"Ver preço"}</div>{p.previous_price!=null&&<div className="text-xs text-muted-foreground line-through">R$ {Number(p.previous_price).toFixed(2)}</div>}<Link to={p.slug?"/product/$slug":"/products"} params={p.slug?{slug:p.slug}:undefined} className="block mt-3"><Button className="w-full">Ver oferta <ArrowRight className="w-4 h-4 ml-2"/></Button></Link></div></div></article>)}</div>}</div></main>;
}