import { useRef, useState } from "react";
import { Upload, FileText, X, CheckCircle2, AlertCircle, Loader2, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { importProductsFromCSV } from "@/lib/supabase/importExport";
import { toast } from "sonner";
import { useNavigate } from "@tanstack/react-router";

export function ProductImport(){const nav=useNavigate();const input=useRef<HTMLInputElement>(null);const[file,setFile]=useState<File|null>(null);const[result,setResult]=useState<any>(null);const[loading,setLoading]=useState(false);
 const template=()=>{const csv='name,description,price,old_price,discount,rating,review_count,status,affiliate_url,shipping,category,marketplace\nProduto Exemplo,Descrição,99.90,129.90,23,4.5,100,draft,https://example.com,paid,Eletrônicos,Shopee';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='modelo_importacao.csv';a.click();};
 const run=async()=>{if(!file)return;setLoading(true);try{setResult(await importProductsFromCSV(await file.text()));toast.success('Importação concluída');}catch(e:any){toast.error(e.message??'Erro ao importar')}finally{setLoading(false)}};
 return <div className="container mx-auto py-12 px-4 max-w-3xl"><div className="flex items-center justify-between mb-6"><div><h1 className="text-3xl font-black uppercase italic">Importar produtos</h1><p className="text-muted-foreground mt-1">Envie um CSV para cadastrar produtos em lote.</p></div><Button variant="ghost" onClick={()=>nav({to:'/admin/products'})}>Voltar</Button></div><div className="rounded-3xl border border-glass-border bg-glass-fallback p-8 space-y-6"><button onClick={()=>input.current?.click()} className="w-full min-h-52 border-2 border-dashed border-muted-foreground/30 rounded-2xl flex flex-col items-center justify-center gap-3 hover:border-primary/60 transition-colors"><input ref={input} type="file" accept=".csv,text/csv" className="hidden" onChange={e=>{setFile(e.target.files?.[0]??null);setResult(null)}}/>{file?<><FileText className="w-10 h-10 text-primary"/><b>{file.name}</b><span className="text-sm text-muted-foreground">Clique para trocar</span></>:<><Upload className="w-10 h-10 text-muted-foreground"/><b>Selecionar arquivo CSV</b><span className="text-sm text-muted-foreground">O sistema valida cada linha antes de inserir</span></>}</button><div className="flex justify-between gap-3"><Button variant="outline" onClick={template}><Download/>Baixar modelo</Button><div className="flex gap-2">{file&&<Button variant="ghost" onClick={()=>setFile(null)}><X/>Remover</Button>}<Button onClick={run} disabled={!file||loading}>{loading?<Loader2 className="animate-spin"/>:<Upload/>}{loading?'Importando...':'Importar'}</Button></div></div>{result&&<div className="rounded-2xl bg-muted/30 p-4 space-y-3"><div className="flex items-center gap-2 font-bold">{result.errors.length?<AlertCircle className="text-yellow-500"/>:<CheckCircle2 className="text-green-500"/>}{result.imported} produtos importados{result.errors.length?` · ${result.errors.length} erros`:''}</div>{result.errors.slice(0,20).map((e:any,i:number)=><div key={i} className="text-sm"><b className="text-destructive">Linha {e.row}:</b> {e.error}</div>)}</div>}</div></div>}
