import { FormEvent, useEffect, useState } from "react";
import { listProducts } from "@/lib/supabase/products";
import { createNativeVideo, getNativeVideo, updateNativeVideo, NativeVideoFormData } from "@/lib/supabase/videos";

export function NativeVideoForm({mode,videoId,onBack}:{mode:"create"|"edit";videoId?:string;onBack:()=>void}){
 const [products,setProducts]=useState<any[]>([]); const [loading,setLoading]=useState(mode==="edit"); const [saving,setSaving]=useState(false);
 const [data,setData]=useState<NativeVideoFormData>({title:"",description:null,video_url:"",thumbnail_url:null,caption:null,product_id:null,affiliate_url:null,status:"draft",is_active:false});
 useEffect(()=>{listProducts({limit:200}).then(r=>setProducts(r.data??[])).catch(console.error);if(mode==="edit"&&videoId)getNativeVideo(videoId).then(v=>{if(v)setData(v as unknown as NativeVideoFormData);setLoading(false)})},[mode,videoId]);
 const set=(k:keyof NativeVideoFormData,v:any)=>setData(d=>({...d,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();if(!data.title.trim()||!data.video_url.trim())return alert("Preencha título e URL do vídeo.");setSaving(true);const r=mode==="create"?await createNativeVideo(data):await updateNativeVideo(videoId!,data);setSaving(false);if(!r.success)return alert(r.error);onBack()}
 if(loading)return <div>Carregando vídeo...</div>;
 return <form className="video-form-premium" onSubmit={submit}><h2>{mode==="create"?"Novo vídeo nativo":"Editar vídeo nativo"}</h2><input required placeholder="Título" value={data.title} onChange={e=>set("title",e.target.value)}/><textarea placeholder="Descrição" value={data.description??""} onChange={e=>set("description",e.target.value||null)}/><input required placeholder="URL do vídeo" value={data.video_url} onChange={e=>set("video_url",e.target.value)}/><input placeholder="URL da thumbnail" value={data.thumbnail_url??""} onChange={e=>set("thumbnail_url",e.target.value||null)}/><input placeholder="Legenda" value={data.caption??""} onChange={e=>set("caption",e.target.value||null)}/><select value={data.product_id??""} onChange={e=>set("product_id",e.target.value||null)}><option value="">Sem produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.title??p.name}</option>)}</select><input placeholder="URL de afiliado" value={data.affiliate_url??""} onChange={e=>set("affiliate_url",e.target.value||null)}/><select value={data.status} onChange={e=>{const s=e.target.value as NativeVideoFormData["status"];set("status",s);set("is_active",s==="published")}}><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="archived">Arquivado</option></select><label><input type="checkbox" checked={data.is_active} onChange={e=>set("is_active",e.target.checked)}/> Ativo</label><div><button type="button" onClick={onBack}>Cancelar</button><button type="submit" disabled={saving}>{saving?"Salvando...":"Salvar vídeo"}</button></div></form>
}
