import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Film, Link2, Package, PlayCircle, Save, Sparkles } from "lucide-react";
import { listProducts } from "@/lib/supabase/products";
import { createNativeVideo, getNativeVideo, updateNativeVideo, NativeVideoFormData } from "@/lib/supabase/videos";

export function NativeVideoForm({mode,videoId,onBack}:{mode:"create"|"edit";videoId?:string;onBack:()=>void}){
 const [products,setProducts]=useState<any[]>([]); const [loading,setLoading]=useState(mode==="edit"); const [saving,setSaving]=useState(false);
 const [data,setData]=useState<NativeVideoFormData>({title:"",description:null,video_url:"",thumbnail_url:null,caption:null,product_id:null,affiliate_url:null,status:"draft",is_active:false});
 useEffect(()=>{listProducts({limit:200}).then(r=>setProducts(r.data??[])).catch(console.error);if(mode==="edit"&&videoId)getNativeVideo(videoId).then(v=>{if(v)setData(v as unknown as NativeVideoFormData);setLoading(false)})},[mode,videoId]);
 const set=(k:keyof NativeVideoFormData,v:any)=>setData(d=>({...d,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();if(!data.title.trim()||!data.video_url.trim())return alert("Preencha título e URL do vídeo.");setSaving(true);const r=mode==="create"?await createNativeVideo(data):await updateNativeVideo(videoId!,data);setSaving(false);if(!r.success)return alert(r.error);onBack()}
 if(loading)return <div className="mx-auto max-w-5xl p-6"><div className="rounded-[2rem] border border-border/60 bg-card/60 p-10 text-center shadow-elevation-1 backdrop-blur-xl">Carregando vídeo...</div></div>;
 return <form onSubmit={submit} className="mx-auto max-w-6xl space-y-6">
   <div className="flex items-center justify-between gap-4"><button type="button" onClick={onBack} className="inline-flex items-center rounded-xl px-3 py-2 text-sm font-semibold text-muted-foreground transition hover:bg-muted hover:text-foreground"><ArrowLeft className="mr-2 h-4 w-4"/>Voltar</button><span className="rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-[10px] font-black uppercase tracking-[.18em] text-primary">Vídeo nativo</span></div>
   <header className="relative overflow-hidden rounded-[2rem] border border-border/60 bg-card/60 p-7 shadow-elevation-1 backdrop-blur-xl md:p-9"><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-primary/10 blur-3xl"/><div className="relative flex items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-primary/20 bg-primary/10 text-primary"><Film className="h-7 w-7"/></div><div><p className="mb-2 text-[10px] font-black uppercase tracking-[.2em] text-primary">Central de vídeos · Conteúdo próprio</p><h2 className="text-3xl font-black tracking-[-.04em] md:text-4xl">{mode==="create"?"Novo vídeo nativo":"Editar vídeo nativo"}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Configure mídia, produto, publicação e distribuição em um único painel.</p></div></div></header>
   <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
    <div className="space-y-6">
     <section className="rounded-3xl border border-border/60 bg-card/60 p-6 shadow-elevation-1 backdrop-blur-xl"><div className="mb-5 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><PlayCircle className="h-5 w-5"/></span><div><h3 className="font-black">Conteúdo</h3><p className="text-xs text-muted-foreground">Defina título, descrição e vídeo.</p></div></div><div className="space-y-4"><input required className="h-12 w-full rounded-xl border border-border/70 bg-background/60 px-4 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" placeholder="Título do vídeo" value={data.title} onChange={e=>set("title",e.target.value)}/><textarea className="min-h-28 w-full rounded-xl border border-border/70 bg-background/60 px-4 py-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" placeholder="Descrição" value={data.description??""} onChange={e=>set("description",e.target.value||null)}/><div className="relative"><Link2 className="absolute left-4 top-3.5 h-4 w-4 text-muted-foreground"/><input required className="h-12 w-full rounded-xl border border-border/70 bg-background/60 pl-11 pr-4 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" placeholder="URL do vídeo" value={data.video_url} onChange={e=>set("video_url",e.target.value)}/></div></div></section>
     <section className="rounded-3xl border border-border/60 bg-card/60 p-6 shadow-elevation-1 backdrop-blur-xl"><div className="mb-5 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Package className="h-5 w-5"/></span><div><h3 className="font-black">Catálogo e mídia</h3><p className="text-xs text-muted-foreground">Associe o produto e personalize a apresentação.</p></div></div><div className="space-y-4"><select className="h-12 w-full rounded-xl border border-border/70 bg-background/60 px-4 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" value={data.product_id??""} onChange={e=>set("product_id",e.target.value||null)}><option value="">Sem produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.title??p.name}</option>)}</select><input className="h-12 w-full rounded-xl border border-border/70 bg-background/60 px-4 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" placeholder="URL da thumbnail" value={data.thumbnail_url??""} onChange={e=>set("thumbnail_url",e.target.value||null)}/><input className="h-12 w-full rounded-xl border border-border/70 bg-background/60 px-4 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" placeholder="Legenda" value={data.caption??""} onChange={e=>set("caption",e.target.value||null)}/><div className="relative"><Link2 className="absolute left-4 top-3.5 h-4 w-4 text-muted-foreground"/><input className="h-12 w-full rounded-xl border border-border/70 bg-background/60 pl-11 pr-4 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" placeholder="URL de afiliado (opcional)" value={data.affiliate_url??""} onChange={e=>set("affiliate_url",e.target.value||null)}/></div></div></section>
    </div>
    <aside className="space-y-6 lg:sticky lg:top-6 lg:self-start"><section className="rounded-3xl border border-border/60 bg-card/60 p-6 shadow-elevation-1 backdrop-blur-xl"><div className="mb-5 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><CheckCircle2 className="h-5 w-5"/></span><div><h3 className="font-black">Publicação</h3><p className="text-xs text-muted-foreground">Controle o estado do vídeo.</p></div></div><select className="h-12 w-full rounded-xl border border-border/70 bg-background/60 px-4 text-sm" value={data.status} onChange={e=>{const s=e.target.value as NativeVideoFormData["status"];set("status",s);set("is_active",s==="published")}}><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="archived">Arquivado</option></select><label className="mt-4 flex items-center justify-between rounded-2xl border border-border/60 bg-background/40 p-4"><span className="text-sm font-bold">Ativo</span><input type="checkbox" className="h-4 w-4 accent-primary" checked={data.is_active} onChange={e=>set("is_active",e.target.checked)}/></label></section><div className="rounded-3xl border border-primary/10 bg-primary/5 p-5 text-sm text-muted-foreground"><div className="mb-2 flex items-center gap-2 font-black text-foreground"><Sparkles className="h-4 w-4 text-primary"/>Pronto para publicar</div>Revise os campos e salve quando o conteúdo estiver completo.</div><div className="space-y-3"><button type="button" onClick={onBack} className="h-12 w-full rounded-xl border border-border bg-card font-bold transition hover:bg-muted">Cancelar</button><button type="submit" disabled={saving} className="h-12 w-full rounded-xl bg-primary px-5 font-black text-primary-foreground shadow-lg shadow-primary/20 transition hover:-translate-y-0.5 hover:shadow-xl">{saving?"Salvando...":"Salvar vídeo"}</button></div></aside>
   </div>
 </form>;
}