import { useEffect, useState } from "react";
import { Check, Filter, RotateCcw, SlidersHorizontal, X } from "lucide-react";
import type { FilterState } from "./useFilters";
import { useFilters } from "./useFilters";

export function FilterDrawer({ isOpen, onClose, pageType, categoryId }: { isOpen: boolean; onClose: () => void; pageType: "search" | "products" | "category" | "deals"; categoryId?: string }) {
  const api = useFilters(pageType, categoryId);
  const [draft, setDraft] = useState<FilterState>(api.filters);
  useEffect(() => { setDraft(api.filters); }, [api.filters, isOpen]);
  if (!isOpen) return null;
  const active = [draft.categories.length, draft.marketplaces.length, draft.minPrice > api.availableFilters.minPrice, draft.maxPrice < api.availableFilters.maxPrice, draft.minDiscount > 0, draft.minRating > 0, draft.freeShipping, draft.bestOffer].filter(Boolean).length;
  const reset: FilterState = { categories: [], minPrice: api.availableFilters.minPrice, maxPrice: api.availableFilters.maxPrice || 10000, minDiscount: 0, minRating: 0, marketplaces: [], freeShipping: false, bestOffer: false };
  const toggle = (key: "categories" | "marketplaces", id: string) => setDraft({ ...draft, [key]: draft[key].includes(id) ? draft[key].filter((x) => x !== id) : [...draft[key], id] });
  return <div className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm" onClick={onClose}><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col border-l border-border bg-background shadow-2xl" onClick={(e) => e.stopPropagation()}><header className="flex items-center justify-between border-b border-border p-5"><div className="flex items-center gap-3"><SlidersHorizontal className="h-5 w-5 text-primary"/><h2 className="font-black">Filtros avançados</h2><span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs text-primary">{active}</span></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-muted"><X className="h-5 w-5"/></button></header><div className="flex-1 space-y-7 overflow-y-auto p-5">
    {pageType !== "category" && <section><h3 className="mb-3 text-sm font-bold">Categorias</h3><div className="max-h-48 space-y-1 overflow-auto">{api.availableFilters.categories.map((x) => <label key={x.id} className="flex cursor-pointer items-center gap-3 rounded-xl p-2 hover:bg-muted/50"><input type="checkbox" checked={draft.categories.includes(x.id)} onChange={() => toggle("categories", x.id)} className="sr-only"/><span className={`flex h-5 w-5 items-center justify-center rounded border ${draft.categories.includes(x.id) ? "border-primary bg-primary text-primary-foreground" : "border-border"}`}>{draft.categories.includes(x.id) && <Check className="h-3.5 w-3.5"/>}</span><span className="flex-1 text-sm">{x.name}</span><span className="text-xs text-muted-foreground">{x.count}</span></label>)}</div></section>}
    <section><h3 className="mb-3 text-sm font-bold">Preço</h3><div className="grid grid-cols-2 gap-3"><input type="number" min={0} value={draft.minPrice} onChange={(e) => setDraft({ ...draft, minPrice: Number(e.target.value) })} className="h-11 rounded-xl border border-border bg-background px-3" placeholder="Mínimo"/><input type="number" min={0} value={draft.maxPrice} onChange={(e) => setDraft({ ...draft, maxPrice: Number(e.target.value) })} className="h-11 rounded-xl border border-border bg-background px-3" placeholder="Máximo"/></div><input aria-label="Preço máximo" type="range" min={api.availableFilters.minPrice} max={api.availableFilters.maxPrice || 10000} value={Math.min(draft.maxPrice, api.availableFilters.maxPrice || 10000)} onChange={(e) => setDraft({ ...draft, maxPrice: Number(e.target.value) })} className="mt-4 w-full accent-primary"/></section>
    <section><h3 className="mb-3 text-sm font-bold">Desconto mínimo: {draft.minDiscount}%</h3><input type="range" min={0} max={100} value={draft.minDiscount} onChange={(e) => setDraft({ ...draft, minDiscount: Number(e.target.value) })} className="w-full accent-primary"/></section>
    <section><h3 className="mb-3 text-sm font-bold">Avaliação mínima</h3><div className="flex gap-2">{[1,2,3,4,5].map((r) => <button key={r} onClick={() => setDraft({ ...draft, minRating: draft.minRating === r ? 0 : r })} className={`rounded-xl border px-3 py-2 text-sm ${draft.minRating === r ? "border-primary bg-primary/10 text-primary" : "border-border"}`}>{r} ★</button>)}</div></section>
    <section><h3 className="mb-3 text-sm font-bold">Marketplaces</h3>{api.availableFilters.marketplaces.map((x) => <label key={x.id} className="flex cursor-pointer items-center gap-3 rounded-xl p-2 hover:bg-muted/50"><input type="checkbox" checked={draft.marketplaces.includes(x.id)} onChange={() => toggle("marketplaces", x.id)} className="h-4 w-4 accent-primary"/><span className="flex-1 text-sm">{x.name}</span><span className="text-xs text-muted-foreground">{x.count}</span></label>)}</section>
    <label className="flex items-center justify-between rounded-2xl border border-border p-4"><span className="text-sm font-bold">Frete grátis</span><input type="checkbox" checked={draft.freeShipping} onChange={(e) => setDraft({ ...draft, freeShipping: e.target.checked })} className="h-5 w-5 accent-primary"/></label><label className="flex items-center justify-between rounded-2xl border border-border p-4"><span className="text-sm font-bold">Melhor oferta</span><input type="checkbox" checked={draft.bestOffer} onChange={(e) => setDraft({ ...draft, bestOffer: e.target.checked })} className="h-5 w-5 accent-primary"/></label>
  </div><footer className="flex gap-3 border-t border-border p-5"><button onClick={() => { setDraft(reset); api.setFilters(reset); api.updateURL(reset); }} className="flex items-center gap-2 rounded-xl border border-border px-4 py-3 text-sm"><RotateCcw className="h-4 w-4"/>Limpar</button><button disabled={api.loading} onClick={() => { api.setFilters(draft); api.updateURL(draft); onClose(); }} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50"><Filter className="h-4 w-4"/>Aplicar filtros</button></footer></aside></div>;
}
