/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BridgeVideosRouteImport } from './routes/bridge-videos'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAutomationsRouteImport } from './routes/admin/automations'
import { Route as AdminBridgeVideosRouteImport } from './routes/admin/bridge-videos'
import { Route as AdminBundlesRouteImport } from './routes/admin/bundles'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminMarketplacesRouteImport } from './routes/admin/marketplaces'
import { Route as AdminMetricsRouteImport } from './routes/admin/metrics'
import { Route as AdminModulesRouteImport } from './routes/admin/modules'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPublishingRouteImport } from './routes/admin/publishing'
import { Route as AdminRecommendationsRouteImport } from './routes/admin/recommendations'
import { Route as AdminReferralsRouteImport } from './routes/admin/referrals'
import { Route as AdminSellerCenterRouteImport } from './routes/admin/seller-center'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSocialChannelsRouteImport } from './routes/admin/social-channels'
import { Route as AdminSocialProofRouteImport } from './routes/admin/social-proof'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSupportKnowledgeRouteImport } from './routes/admin/support-knowledge'
import { Route as AdminTelegramRouteImport } from './routes/admin/telegram'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminV1AuditRouteImport } from './routes/admin/v1-audit'
import { Route as AdminVideosRouteImport } from './routes/admin/videos'
import { Route as ApiScheduledPublishingRouteImport } from './routes/api/scheduled-publishing'
import { Route as BundleSlugRouteImport } from './routes/bundle/$slug'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as DevSocialProofPreviewRouteImport } from './routes/dev.social-proof-preview'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as AdminMarketplacesIdRouteImport } from './routes/admin/marketplaces.$id'
import { Route as AdminMarketplacesNewRouteImport } from './routes/admin/marketplaces.new'
import { Route as AdminOffersNewRouteImport } from './routes/admin/offers.new'
import { Route as AdminProductsExportRouteImport } from './routes/admin/products.export'
import { Route as AdminProductsImportRouteImport } from './routes/admin/products.import'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products.new'
import { Route as AdminVideosNewRouteImport } from './routes/admin/videos.new'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products.$id.edit'
import { Route as AdminVideosIdEditRouteImport } from './routes/admin/videos.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeVideosRoute = BridgeVideosRouteImport.update({
  id: '/bridge-videos',
  path: '/bridge-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationsRoute = AdminAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBridgeVideosRoute = AdminBridgeVideosRouteImport.update({
  id: '/bridge-videos',
  path: '/bridge-videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBundlesRoute = AdminBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplacesRoute = AdminMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublishingRoute = AdminPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellerCenterRoute = AdminSellerCenterRouteImport.update({
  id: '/seller-center',
  path: '/seller-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialChannelsRoute = AdminSocialChannelsRouteImport.update({
  id: '/social-channels',
  path: '/social-channels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialProofRoute = AdminSocialProofRouteImport.update({
  id: '/social-proof',
  path: '/social-proof',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportKnowledgeRoute = AdminSupportKnowledgeRouteImport.update({
  id: '/support-knowledge',
  path: '/support-knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminV1AuditRoute = AdminV1AuditRouteImport.update({
  id: '/v1-audit',
  path: '/v1-audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const ApiScheduledPublishingRoute = ApiScheduledPublishingRouteImport.update({
  id: '/api/scheduled-publishing',
  path: '/api/scheduled-publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleSlugRoute = BundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSocialProofPreviewRoute = DevSocialProofPreviewRouteImport.update({
  id: '/dev/social-proof-preview',
  path: '/dev/social-proof-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketplacesIdRoute = AdminMarketplacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMarketplacesRoute,
} as any)
const AdminMarketplacesNewRoute = AdminMarketplacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMarketplacesRoute,
} as any)
const AdminOffersNewRoute = AdminOffersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminOffersRoute,
} as any)
const AdminProductsExportRoute = AdminProductsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsImportRoute = AdminProductsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminVideosNewRoute = AdminVideosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminVideosRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminVideosIdEditRoute = AdminVideosIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminVideosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/bridge-videos': typeof BridgeVideosRoute
  '/categories': typeof CategoriesRoute
  '/deals': typeof DealsRoute
  '/favorites': typeof FavoritesRoute
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/bridge-videos': typeof AdminBridgeVideosRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/marketplaces': typeof AdminMarketplacesRouteWithChildren
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/publishing': typeof AdminPublishingRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/seller-center': typeof AdminSellerCenterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social-channels': typeof AdminSocialChannelsRoute
  '/admin/social-proof': typeof AdminSocialProofRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support-knowledge': typeof AdminSupportKnowledgeRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/v1-audit': typeof AdminV1AuditRoute
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/api/scheduled-publishing': typeof ApiScheduledPublishingRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/social-proof-preview': typeof DevSocialProofPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/marketplaces/$id': typeof AdminMarketplacesIdRoute
  '/admin/marketplaces/new': typeof AdminMarketplacesNewRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/products/export': typeof AdminProductsExportRoute
  '/admin/products/import': typeof AdminProductsImportRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/videos/$id/edit': typeof AdminVideosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/bridge-videos': typeof BridgeVideosRoute
  '/categories': typeof CategoriesRoute
  '/deals': typeof DealsRoute
  '/favorites': typeof FavoritesRoute
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/bridge-videos': typeof AdminBridgeVideosRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/marketplaces': typeof AdminMarketplacesRouteWithChildren
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/publishing': typeof AdminPublishingRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/seller-center': typeof AdminSellerCenterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social-channels': typeof AdminSocialChannelsRoute
  '/admin/social-proof': typeof AdminSocialProofRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support-knowledge': typeof AdminSupportKnowledgeRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/v1-audit': typeof AdminV1AuditRoute
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/api/scheduled-publishing': typeof ApiScheduledPublishingRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/social-proof-preview': typeof DevSocialProofPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/marketplaces/$id': typeof AdminMarketplacesIdRoute
  '/admin/marketplaces/new': typeof AdminMarketplacesNewRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/products/export': typeof AdminProductsExportRoute
  '/admin/products/import': typeof AdminProductsImportRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/videos/$id/edit': typeof AdminVideosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/bridge-videos': typeof BridgeVideosRoute
  '/categories': typeof CategoriesRoute
  '/deals': typeof DealsRoute
  '/favorites': typeof FavoritesRoute
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/bridge-videos': typeof AdminBridgeVideosRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/marketplaces': typeof AdminMarketplacesRouteWithChildren
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/publishing': typeof AdminPublishingRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/seller-center': typeof AdminSellerCenterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social-channels': typeof AdminSocialChannelsRoute
  '/admin/social-proof': typeof AdminSocialProofRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support-knowledge': typeof AdminSupportKnowledgeRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/v1-audit': typeof AdminV1AuditRoute
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/api/scheduled-publishing': typeof ApiScheduledPublishingRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/social-proof-preview': typeof DevSocialProofPreviewRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/marketplaces/$id': typeof AdminMarketplacesIdRoute
  '/admin/marketplaces/new': typeof AdminMarketplacesNewRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/products/export': typeof AdminProductsExportRoute
  '/admin/products/import': typeof AdminProductsImportRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/videos/$id/edit': typeof AdminVideosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/bridge-videos'
    | '/categories'
    | '/deals'
    | '/favorites'
    | '/feed'
    | '/history'
    | '/leaderboard'
    | '/products'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/trending'
    | '/videos'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/automations'
    | '/admin/bridge-videos'
    | '/admin/bundles'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/integrations'
    | '/admin/marketplaces'
    | '/admin/metrics'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/products'
    | '/admin/publishing'
    | '/admin/recommendations'
    | '/admin/referrals'
    | '/admin/seller-center'
    | '/admin/settings'
    | '/admin/social-channels'
    | '/admin/social-proof'
    | '/admin/support'
    | '/admin/support-knowledge'
    | '/admin/telegram'
    | '/admin/users'
    | '/admin/v1-audit'
    | '/admin/videos'
    | '/api/scheduled-publishing'
    | '/bundle/$slug'
    | '/category/$slug'
    | '/dev/social-proof-preview'
    | '/product/$slug'
    | '/admin/marketplaces/$id'
    | '/admin/marketplaces/new'
    | '/admin/offers/new'
    | '/admin/products/export'
    | '/admin/products/import'
    | '/admin/products/new'
    | '/admin/videos/new'
    | '/admin/products/$id/edit'
    | '/admin/videos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/bridge-videos'
    | '/categories'
    | '/deals'
    | '/favorites'
    | '/feed'
    | '/history'
    | '/leaderboard'
    | '/products'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/trending'
    | '/videos'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/automations'
    | '/admin/bridge-videos'
    | '/admin/bundles'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/integrations'
    | '/admin/marketplaces'
    | '/admin/metrics'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/products'
    | '/admin/publishing'
    | '/admin/recommendations'
    | '/admin/referrals'
    | '/admin/seller-center'
    | '/admin/settings'
    | '/admin/social-channels'
    | '/admin/social-proof'
    | '/admin/support'
    | '/admin/support-knowledge'
    | '/admin/telegram'
    | '/admin/users'
    | '/admin/v1-audit'
    | '/admin/videos'
    | '/api/scheduled-publishing'
    | '/bundle/$slug'
    | '/category/$slug'
    | '/dev/social-proof-preview'
    | '/product/$slug'
    | '/admin/marketplaces/$id'
    | '/admin/marketplaces/new'
    | '/admin/offers/new'
    | '/admin/products/export'
    | '/admin/products/import'
    | '/admin/products/new'
    | '/admin/videos/new'
    | '/admin/products/$id/edit'
    | '/admin/videos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/bridge-videos'
    | '/categories'
    | '/deals'
    | '/favorites'
    | '/feed'
    | '/history'
    | '/leaderboard'
    | '/products'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/trending'
    | '/videos'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/automations'
    | '/admin/bridge-videos'
    | '/admin/bundles'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/integrations'
    | '/admin/marketplaces'
    | '/admin/metrics'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/products'
    | '/admin/publishing'
    | '/admin/recommendations'
    | '/admin/referrals'
    | '/admin/seller-center'
    | '/admin/settings'
    | '/admin/social-channels'
    | '/admin/social-proof'
    | '/admin/support'
    | '/admin/support-knowledge'
    | '/admin/telegram'
    | '/admin/users'
    | '/admin/v1-audit'
    | '/admin/videos'
    | '/api/scheduled-publishing'
    | '/bundle/$slug'
    | '/category/$slug'
    | '/dev/social-proof-preview'
    | '/product/$slug'
    | '/admin/marketplaces/$id'
    | '/admin/marketplaces/new'
    | '/admin/offers/new'
    | '/admin/products/export'
    | '/admin/products/import'
    | '/admin/products/new'
    | '/admin/videos/new'
    | '/admin/products/$id/edit'
    | '/admin/videos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  BridgeVideosRoute: typeof BridgeVideosRoute
  CategoriesRoute: typeof CategoriesRoute
  DealsRoute: typeof DealsRoute
  FavoritesRoute: typeof FavoritesRoute
  FeedRoute: typeof FeedRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  TrendingRoute: typeof TrendingRoute
  VideosRoute: typeof VideosRoute
  ApiScheduledPublishingRoute: typeof ApiScheduledPublishingRoute
  BundleSlugRoute: typeof BundleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DevSocialProofPreviewRoute: typeof DevSocialProofPreviewRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge-videos': {
      id: '/bridge-videos'
      path: '/bridge-videos'
      fullPath: '/bridge-videos'
      preLoaderRoute: typeof BridgeVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automations': {
      id: '/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AdminAutomationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bridge-videos': {
      id: '/admin/bridge-videos'
      path: '/bridge-videos'
      fullPath: '/admin/bridge-videos'
      preLoaderRoute: typeof AdminBridgeVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bundles': {
      id: '/admin/bundles'
      path: '/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AdminBundlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplaces': {
      id: '/admin/marketplaces'
      path: '/marketplaces'
      fullPath: '/admin/marketplaces'
      preLoaderRoute: typeof AdminMarketplacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publishing': {
      id: '/admin/publishing'
      path: '/publishing'
      fullPath: '/admin/publishing'
      preLoaderRoute: typeof AdminPublishingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seller-center': {
      id: '/admin/seller-center'
      path: '/seller-center'
      fullPath: '/admin/seller-center'
      preLoaderRoute: typeof AdminSellerCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social-channels': {
      id: '/admin/social-channels'
      path: '/social-channels'
      fullPath: '/admin/social-channels'
      preLoaderRoute: typeof AdminSocialChannelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social-proof': {
      id: '/admin/social-proof'
      path: '/social-proof'
      fullPath: '/admin/social-proof'
      preLoaderRoute: typeof AdminSocialProofRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support-knowledge': {
      id: '/admin/support-knowledge'
      path: '/support-knowledge'
      fullPath: '/admin/support-knowledge'
      preLoaderRoute: typeof AdminSupportKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/v1-audit': {
      id: '/admin/v1-audit'
      path: '/v1-audit'
      fullPath: '/admin/v1-audit'
      preLoaderRoute: typeof AdminV1AuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/scheduled-publishing': {
      id: '/api/scheduled-publishing'
      path: '/api/scheduled-publishing'
      fullPath: '/api/scheduled-publishing'
      preLoaderRoute: typeof ApiScheduledPublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/$slug': {
      id: '/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/bundle/$slug'
      preLoaderRoute: typeof BundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/social-proof-preview': {
      id: '/dev/social-proof-preview'
      path: '/dev/social-proof-preview'
      fullPath: '/dev/social-proof-preview'
      preLoaderRoute: typeof DevSocialProofPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketplaces/$id': {
      id: '/admin/marketplaces/$id'
      path: '/$id'
      fullPath: '/admin/marketplaces/$id'
      preLoaderRoute: typeof AdminMarketplacesIdRouteImport
      parentRoute: typeof AdminMarketplacesRoute
    }
    '/admin/marketplaces/new': {
      id: '/admin/marketplaces/new'
      path: '/new'
      fullPath: '/admin/marketplaces/new'
      preLoaderRoute: typeof AdminMarketplacesNewRouteImport
      parentRoute: typeof AdminMarketplacesRoute
    }
    '/admin/offers/new': {
      id: '/admin/offers/new'
      path: '/new'
      fullPath: '/admin/offers/new'
      preLoaderRoute: typeof AdminOffersNewRouteImport
      parentRoute: typeof AdminOffersRoute
    }
    '/admin/products/export': {
      id: '/admin/products/export'
      path: '/export'
      fullPath: '/admin/products/export'
      preLoaderRoute: typeof AdminProductsExportRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/import': {
      id: '/admin/products/import'
      path: '/import'
      fullPath: '/admin/products/import'
      preLoaderRoute: typeof AdminProductsImportRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/videos/new': {
      id: '/admin/videos/new'
      path: '/new'
      fullPath: '/admin/videos/new'
      preLoaderRoute: typeof AdminVideosNewRouteImport
      parentRoute: typeof AdminVideosRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/videos/$id/edit': {
      id: '/admin/videos/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/videos/$id/edit'
      preLoaderRoute: typeof AdminVideosIdEditRouteImport
      parentRoute: typeof AdminVideosRoute
    }
  }
}

interface AdminMarketplacesRouteChildren {
  AdminMarketplacesIdRoute: typeof AdminMarketplacesIdRoute
  AdminMarketplacesNewRoute: typeof AdminMarketplacesNewRoute
}

const AdminMarketplacesRouteChildren: AdminMarketplacesRouteChildren = {
  AdminMarketplacesIdRoute: AdminMarketplacesIdRoute,
  AdminMarketplacesNewRoute: AdminMarketplacesNewRoute,
}

const AdminMarketplacesRouteWithChildren =
  AdminMarketplacesRoute._addFileChildren(AdminMarketplacesRouteChildren)

interface AdminOffersRouteChildren {
  AdminOffersNewRoute: typeof AdminOffersNewRoute
}

const AdminOffersRouteChildren: AdminOffersRouteChildren = {
  AdminOffersNewRoute: AdminOffersNewRoute,
}

const AdminOffersRouteWithChildren = AdminOffersRoute._addFileChildren(
  AdminOffersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsExportRoute: typeof AdminProductsExportRoute
  AdminProductsImportRoute: typeof AdminProductsImportRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsExportRoute: AdminProductsExportRoute,
  AdminProductsImportRoute: AdminProductsImportRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminVideosRouteChildren {
  AdminVideosNewRoute: typeof AdminVideosNewRoute
  AdminVideosIdEditRoute: typeof AdminVideosIdEditRoute
}

const AdminVideosRouteChildren: AdminVideosRouteChildren = {
  AdminVideosNewRoute: AdminVideosNewRoute,
  AdminVideosIdEditRoute: AdminVideosIdEditRoute,
}

const AdminVideosRouteWithChildren = AdminVideosRoute._addFileChildren(
  AdminVideosRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAutomationsRoute: typeof AdminAutomationsRoute
  AdminBridgeVideosRoute: typeof AdminBridgeVideosRoute
  AdminBundlesRoute: typeof AdminBundlesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminMarketplacesRoute: typeof AdminMarketplacesRouteWithChildren
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOffersRoute: typeof AdminOffersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminPublishingRoute: typeof AdminPublishingRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminSellerCenterRoute: typeof AdminSellerCenterRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSocialChannelsRoute: typeof AdminSocialChannelsRoute
  AdminSocialProofRoute: typeof AdminSocialProofRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSupportKnowledgeRoute: typeof AdminSupportKnowledgeRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminV1AuditRoute: typeof AdminV1AuditRoute
  AdminVideosRoute: typeof AdminVideosRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminAutomationsRoute: AdminAutomationsRoute,
  AdminBridgeVideosRoute: AdminBridgeVideosRoute,
  AdminBundlesRoute: AdminBundlesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminMarketplacesRoute: AdminMarketplacesRouteWithChildren,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOffersRoute: AdminOffersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminPublishingRoute: AdminPublishingRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminSellerCenterRoute: AdminSellerCenterRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSocialChannelsRoute: AdminSocialChannelsRoute,
  AdminSocialProofRoute: AdminSocialProofRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSupportKnowledgeRoute: AdminSupportKnowledgeRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminV1AuditRoute: AdminV1AuditRoute,
  AdminVideosRoute: AdminVideosRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  BridgeVideosRoute: BridgeVideosRoute,
  CategoriesRoute: CategoriesRoute,
  DealsRoute: DealsRoute,
  FavoritesRoute: FavoritesRoute,
  FeedRoute: FeedRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  TrendingRoute: TrendingRoute,
  VideosRoute: VideosRoute,
  ApiScheduledPublishingRoute: ApiScheduledPublishingRoute,
  BundleSlugRoute: BundleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  DevSocialProofPreviewRoute: DevSocialProofPreviewRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
