import { Activity, Bell, CheckCircle2, CircleOff, Package, PlaySquare, ShoppingBag, Sparkles, Tag, Users } from "lucide-react";
import type { AdminIntegrationState, IntegrationDbStatus } from "../core/database";

type Props = { state: AdminIntegrationState; status: IntegrationDbStatus[] };
const sectors = [["products", "Produtos", Package], ["videos", "Vídeos", PlaySquare], ["videoBridge", "Video Bridge", Activity], ["marketplaces", "Marketplaces", ShoppingBag], ["offers", "Ofertas", Tag], ["socialProof", "Social Proof", Users], ["notifications", "Notificações", Bell]] as const;
export function EcosystemStatus({ state, status }: Props) {
  const active = status.filter((r) => r.status === "active").length;
  const errors = status.filter((r) => r.status === "error").length;
  return <section className="secure-ecosystem rounded-[2rem] border border-glass-border bg-glass-fallback p-5 backdrop-blur-xl md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-primary"><Sparkles className="h-4 w-4" /><span className="text-[10px] font-black uppercase tracking-[.2em]">Ecosystem Control</span></div><h2 className="mt-1 text-2xl font-black tracking-tight">Status do ecossistema</h2><p className="mt-1 text-sm text-muted-foreground">Disponibilidade derivada somente de conexões confirmadas.</p></div><div className="grid grid-cols-3 gap-2 text-center"><Metric label="Ativas" value={active} /><Metric label="Setores" value={Object.values(state.sectors).filter(Boolean).length} /><Metric label="Erros" value={errors} /></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{sectors.map(([id, label, Icon]) => { const enabled = state.sectors[id]; return <div key={id} className={`rounded-2xl border p-4 transition-all ${enabled ? "border-emerald-500/20 bg-emerald-500/5" : "border-glass-border bg-background/20 opacity-70"}`}><div className="flex items-center gap-3"><Icon className={`h-4 w-4 ${enabled ? "text-emerald-500" : "text-muted-foreground"}`} /><span className="text-sm font-bold">{label}</span>{enabled ? <CheckCircle2 className="ml-auto h-4 w-4 text-emerald-500" /> : <CircleOff className="ml-auto h-4 w-4 text-muted-foreground" />}</div><p className="mt-2 text-[11px] text-muted-foreground">{enabled ? "Ativado" : "Aguardando integração"}</p></div>; })}</div></section>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-glass-border bg-background/20 px-3 py-2"><div className="text-lg font-black">{value}</div><div className="text-[9px] font-bold uppercase tracking-wider text-muted-foreground">{label}</div></div>; }
